/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CreateManufacturerCommand,
  HttpValidationProblemDetails,
  ManufacturerDto,
  UpdateManufacturerCommand,
} from "../../models";

import { api } from "../../orval-custom-instance";
import type { ErrorType } from "../../orval-custom-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getManufacturers = (
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<ManufacturerDto[]>(
    { url: `/api/Admin/V1/Manufacturers`, method: "GET", signal },
    options,
  );
};

export const getGetManufacturersQueryKey = () => {
  return [`/api/Admin/V1/Manufacturers`] as const;
};

export const getGetManufacturersQueryOptions = <
  TData = Awaited<ReturnType<typeof getManufacturers>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getManufacturers>>, TError, TData>
  >;
  request?: SecondParameter<typeof api>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetManufacturersQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getManufacturers>>
  > = ({ signal }) => getManufacturers(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getManufacturers>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetManufacturersQueryResult = NonNullable<
  Awaited<ReturnType<typeof getManufacturers>>
>;
export type GetManufacturersQueryError = ErrorType<unknown>;

export function useGetManufacturers<
  TData = Awaited<ReturnType<typeof getManufacturers>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getManufacturers>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getManufacturers>>,
          TError,
          Awaited<ReturnType<typeof getManufacturers>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetManufacturers<
  TData = Awaited<ReturnType<typeof getManufacturers>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getManufacturers>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getManufacturers>>,
          TError,
          Awaited<ReturnType<typeof getManufacturers>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetManufacturers<
  TData = Awaited<ReturnType<typeof getManufacturers>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getManufacturers>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetManufacturers<
  TData = Awaited<ReturnType<typeof getManufacturers>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getManufacturers>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetManufacturersQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const createManufacturer = (
  createManufacturerCommand: CreateManufacturerCommand,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<number>(
    {
      url: `/api/Admin/V1/Manufacturers`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createManufacturerCommand,
      signal,
    },
    options,
  );
};

export const getCreateManufacturerMutationOptions = <
  TError = ErrorType<HttpValidationProblemDetails>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createManufacturer>>,
    TError,
    { data: CreateManufacturerCommand },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createManufacturer>>,
  TError,
  { data: CreateManufacturerCommand },
  TContext
> => {
  const mutationKey = ["createManufacturer"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createManufacturer>>,
    { data: CreateManufacturerCommand }
  > = (props) => {
    const { data } = props ?? {};

    return createManufacturer(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateManufacturerMutationResult = NonNullable<
  Awaited<ReturnType<typeof createManufacturer>>
>;
export type CreateManufacturerMutationBody = CreateManufacturerCommand;
export type CreateManufacturerMutationError =
  ErrorType<HttpValidationProblemDetails>;

export const useCreateManufacturer = <
  TError = ErrorType<HttpValidationProblemDetails>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createManufacturer>>,
      TError,
      { data: CreateManufacturerCommand },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createManufacturer>>,
  TError,
  { data: CreateManufacturerCommand },
  TContext
> => {
  const mutationOptions = getCreateManufacturerMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const getManufacturerById = (
  id: number,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<ManufacturerDto>(
    { url: `/api/Admin/V1/Manufacturers/${id}`, method: "GET", signal },
    options,
  );
};

export const getGetManufacturerByIdQueryKey = (id?: number) => {
  return [`/api/Admin/V1/Manufacturers/${id}`] as const;
};

export const getGetManufacturerByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getManufacturerById>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getManufacturerById>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetManufacturerByIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getManufacturerById>>
  > = ({ signal }) => getManufacturerById(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getManufacturerById>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetManufacturerByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getManufacturerById>>
>;
export type GetManufacturerByIdQueryError = ErrorType<void>;

export function useGetManufacturerById<
  TData = Awaited<ReturnType<typeof getManufacturerById>>,
  TError = ErrorType<void>,
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getManufacturerById>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getManufacturerById>>,
          TError,
          Awaited<ReturnType<typeof getManufacturerById>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetManufacturerById<
  TData = Awaited<ReturnType<typeof getManufacturerById>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getManufacturerById>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getManufacturerById>>,
          TError,
          Awaited<ReturnType<typeof getManufacturerById>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetManufacturerById<
  TData = Awaited<ReturnType<typeof getManufacturerById>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getManufacturerById>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetManufacturerById<
  TData = Awaited<ReturnType<typeof getManufacturerById>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getManufacturerById>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetManufacturerByIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const updateManufacturer = (
  id: number,
  updateManufacturerCommand: UpdateManufacturerCommand,
  options?: SecondParameter<typeof api>,
) => {
  return api<void>(
    {
      url: `/api/Admin/V1/Manufacturers/${id}`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: updateManufacturerCommand,
    },
    options,
  );
};

export const getUpdateManufacturerMutationOptions = <
  TError = ErrorType<HttpValidationProblemDetails | void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateManufacturer>>,
    TError,
    { id: number; data: UpdateManufacturerCommand },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateManufacturer>>,
  TError,
  { id: number; data: UpdateManufacturerCommand },
  TContext
> => {
  const mutationKey = ["updateManufacturer"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateManufacturer>>,
    { id: number; data: UpdateManufacturerCommand }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateManufacturer(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateManufacturerMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateManufacturer>>
>;
export type UpdateManufacturerMutationBody = UpdateManufacturerCommand;
export type UpdateManufacturerMutationError =
  ErrorType<HttpValidationProblemDetails | void>;

export const useUpdateManufacturer = <
  TError = ErrorType<HttpValidationProblemDetails | void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateManufacturer>>,
      TError,
      { id: number; data: UpdateManufacturerCommand },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateManufacturer>>,
  TError,
  { id: number; data: UpdateManufacturerCommand },
  TContext
> => {
  const mutationOptions = getUpdateManufacturerMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const deleteManufacturer = (
  id: number,
  options?: SecondParameter<typeof api>,
) => {
  return api<void>(
    { url: `/api/Admin/V1/Manufacturers/${id}`, method: "DELETE" },
    options,
  );
};

export const getDeleteManufacturerMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteManufacturer>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteManufacturer>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["deleteManufacturer"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteManufacturer>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return deleteManufacturer(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteManufacturerMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteManufacturer>>
>;

export type DeleteManufacturerMutationError = ErrorType<void>;

export const useDeleteManufacturer = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteManufacturer>>,
      TError,
      { id: number },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteManufacturer>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getDeleteManufacturerMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
