/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  BlogDto,
  CreateBlogCommand,
  GetBlogsListParams,
  GetBlogsParams,
  PaginatedListOfBlogListDto,
  PaginatedListOfPublicBlogListDto,
  PublicBlogDto,
  UpdateBlogCommand,
} from "../../models";

import { api } from "../../orval-custom-instance";
import type { ErrorType } from "../../orval-custom-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Retrieves a paginated list of blog posts for public viewing. Supports search functionality and sorting.
            
**Search:**
Searches across blog title, short description, and slug fields.
            
**Sorting:**
Use ?sortBy=field&sortDirection=asc|desc
Supported fields: created, title, slug, lastModified
Default sort: created (descending)
            
**Examples:**
- GET /api/V1/Blogs?pageNumber=1&pageSize=10
- GET /api/V1/Blogs?search=tutorial&sortBy=title&sortDirection=asc
- GET /api/V1/Blogs?pageSize=5&sortBy=created&sortDirection=desc
 * @summary Get blog posts with optional search, sorting, and pagination
 */
export const getBlogs = (
  params?: GetBlogsParams,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<PaginatedListOfPublicBlogListDto>(
    { url: `/api/V1/Blogs`, method: "GET", params, signal },
    options,
  );
};

export const getGetBlogsQueryKey = (params?: GetBlogsParams) => {
  return [`/api/V1/Blogs`, ...(params ? [params] : [])] as const;
};

export const getGetBlogsQueryOptions = <
  TData = Awaited<ReturnType<typeof getBlogs>>,
  TError = ErrorType<unknown>,
>(
  params?: GetBlogsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getBlogs>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetBlogsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getBlogs>>> = ({
    signal,
  }) => getBlogs(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getBlogs>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetBlogsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getBlogs>>
>;
export type GetBlogsQueryError = ErrorType<unknown>;

export function useGetBlogs<
  TData = Awaited<ReturnType<typeof getBlogs>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetBlogsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getBlogs>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBlogs>>,
          TError,
          Awaited<ReturnType<typeof getBlogs>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetBlogs<
  TData = Awaited<ReturnType<typeof getBlogs>>,
  TError = ErrorType<unknown>,
>(
  params?: GetBlogsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getBlogs>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBlogs>>,
          TError,
          Awaited<ReturnType<typeof getBlogs>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetBlogs<
  TData = Awaited<ReturnType<typeof getBlogs>>,
  TError = ErrorType<unknown>,
>(
  params?: GetBlogsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getBlogs>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get blog posts with optional search, sorting, and pagination
 */

export function useGetBlogs<
  TData = Awaited<ReturnType<typeof getBlogs>>,
  TError = ErrorType<unknown>,
>(
  params?: GetBlogsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getBlogs>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetBlogsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get a blog post by ID
 */
export const getBlogById = (
  id: number,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<PublicBlogDto>(
    { url: `/api/V1/Blogs/${id}`, method: "GET", signal },
    options,
  );
};

export const getGetBlogByIdQueryKey = (id?: number) => {
  return [`/api/V1/Blogs/${id}`] as const;
};

export const getGetBlogByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getBlogById>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getBlogById>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetBlogByIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getBlogById>>> = ({
    signal,
  }) => getBlogById(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getBlogById>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetBlogByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getBlogById>>
>;
export type GetBlogByIdQueryError = ErrorType<void>;

export function useGetBlogById<
  TData = Awaited<ReturnType<typeof getBlogById>>,
  TError = ErrorType<void>,
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getBlogById>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBlogById>>,
          TError,
          Awaited<ReturnType<typeof getBlogById>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetBlogById<
  TData = Awaited<ReturnType<typeof getBlogById>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getBlogById>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBlogById>>,
          TError,
          Awaited<ReturnType<typeof getBlogById>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetBlogById<
  TData = Awaited<ReturnType<typeof getBlogById>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getBlogById>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get a blog post by ID
 */

export function useGetBlogById<
  TData = Awaited<ReturnType<typeof getBlogById>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getBlogById>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetBlogByIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get a blog post by slug
 */
export const getBlogBySlug = (
  slug: string,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<PublicBlogDto>(
    { url: `/api/V1/Blogs/slug/${slug}`, method: "GET", signal },
    options,
  );
};

export const getGetBlogBySlugQueryKey = (slug?: string) => {
  return [`/api/V1/Blogs/slug/${slug}`] as const;
};

export const getGetBlogBySlugQueryOptions = <
  TData = Awaited<ReturnType<typeof getBlogBySlug>>,
  TError = ErrorType<void>,
>(
  slug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getBlogBySlug>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetBlogBySlugQueryKey(slug);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getBlogBySlug>>> = ({
    signal,
  }) => getBlogBySlug(slug, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!slug,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getBlogBySlug>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetBlogBySlugQueryResult = NonNullable<
  Awaited<ReturnType<typeof getBlogBySlug>>
>;
export type GetBlogBySlugQueryError = ErrorType<void>;

export function useGetBlogBySlug<
  TData = Awaited<ReturnType<typeof getBlogBySlug>>,
  TError = ErrorType<void>,
>(
  slug: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getBlogBySlug>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBlogBySlug>>,
          TError,
          Awaited<ReturnType<typeof getBlogBySlug>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetBlogBySlug<
  TData = Awaited<ReturnType<typeof getBlogBySlug>>,
  TError = ErrorType<void>,
>(
  slug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getBlogBySlug>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBlogBySlug>>,
          TError,
          Awaited<ReturnType<typeof getBlogBySlug>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetBlogBySlug<
  TData = Awaited<ReturnType<typeof getBlogBySlug>>,
  TError = ErrorType<void>,
>(
  slug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getBlogBySlug>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get a blog post by slug
 */

export function useGetBlogBySlug<
  TData = Awaited<ReturnType<typeof getBlogBySlug>>,
  TError = ErrorType<void>,
>(
  slug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getBlogBySlug>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetBlogBySlugQueryOptions(slug, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getBlogsList = (
  params?: GetBlogsListParams,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<PaginatedListOfBlogListDto>(
    { url: `/api/Admin/V1/Blogs`, method: "GET", params, signal },
    options,
  );
};

export const getGetBlogsListQueryKey = (params?: GetBlogsListParams) => {
  return [`/api/Admin/V1/Blogs`, ...(params ? [params] : [])] as const;
};

export const getGetBlogsListQueryOptions = <
  TData = Awaited<ReturnType<typeof getBlogsList>>,
  TError = ErrorType<unknown>,
>(
  params?: GetBlogsListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getBlogsList>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetBlogsListQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getBlogsList>>> = ({
    signal,
  }) => getBlogsList(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getBlogsList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetBlogsListQueryResult = NonNullable<
  Awaited<ReturnType<typeof getBlogsList>>
>;
export type GetBlogsListQueryError = ErrorType<unknown>;

export function useGetBlogsList<
  TData = Awaited<ReturnType<typeof getBlogsList>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetBlogsListParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getBlogsList>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBlogsList>>,
          TError,
          Awaited<ReturnType<typeof getBlogsList>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetBlogsList<
  TData = Awaited<ReturnType<typeof getBlogsList>>,
  TError = ErrorType<unknown>,
>(
  params?: GetBlogsListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getBlogsList>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBlogsList>>,
          TError,
          Awaited<ReturnType<typeof getBlogsList>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetBlogsList<
  TData = Awaited<ReturnType<typeof getBlogsList>>,
  TError = ErrorType<unknown>,
>(
  params?: GetBlogsListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getBlogsList>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetBlogsList<
  TData = Awaited<ReturnType<typeof getBlogsList>>,
  TError = ErrorType<unknown>,
>(
  params?: GetBlogsListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getBlogsList>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetBlogsListQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const createBlog = (
  createBlogCommand: CreateBlogCommand,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<number>(
    {
      url: `/api/Admin/V1/Blogs`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createBlogCommand,
      signal,
    },
    options,
  );
};

export const getCreateBlogMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createBlog>>,
    TError,
    { data: CreateBlogCommand },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createBlog>>,
  TError,
  { data: CreateBlogCommand },
  TContext
> => {
  const mutationKey = ["createBlog"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createBlog>>,
    { data: CreateBlogCommand }
  > = (props) => {
    const { data } = props ?? {};

    return createBlog(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateBlogMutationResult = NonNullable<
  Awaited<ReturnType<typeof createBlog>>
>;
export type CreateBlogMutationBody = CreateBlogCommand;
export type CreateBlogMutationError = ErrorType<unknown>;

export const useCreateBlog = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createBlog>>,
      TError,
      { data: CreateBlogCommand },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createBlog>>,
  TError,
  { data: CreateBlogCommand },
  TContext
> => {
  const mutationOptions = getCreateBlogMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const getBlog = (
  id: number,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<BlogDto>(
    { url: `/api/Admin/V1/Blogs/${id}`, method: "GET", signal },
    options,
  );
};

export const getGetBlogQueryKey = (id?: number) => {
  return [`/api/Admin/V1/Blogs/${id}`] as const;
};

export const getGetBlogQueryOptions = <
  TData = Awaited<ReturnType<typeof getBlog>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getBlog>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetBlogQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getBlog>>> = ({
    signal,
  }) => getBlog(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getBlog>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetBlogQueryResult = NonNullable<
  Awaited<ReturnType<typeof getBlog>>
>;
export type GetBlogQueryError = ErrorType<void>;

export function useGetBlog<
  TData = Awaited<ReturnType<typeof getBlog>>,
  TError = ErrorType<void>,
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getBlog>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBlog>>,
          TError,
          Awaited<ReturnType<typeof getBlog>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetBlog<
  TData = Awaited<ReturnType<typeof getBlog>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getBlog>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBlog>>,
          TError,
          Awaited<ReturnType<typeof getBlog>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetBlog<
  TData = Awaited<ReturnType<typeof getBlog>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getBlog>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetBlog<
  TData = Awaited<ReturnType<typeof getBlog>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getBlog>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetBlogQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const updateBlog = (
  id: number,
  updateBlogCommand: UpdateBlogCommand,
  options?: SecondParameter<typeof api>,
) => {
  return api<void>(
    {
      url: `/api/Admin/V1/Blogs/${id}`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: updateBlogCommand,
    },
    options,
  );
};

export const getUpdateBlogMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateBlog>>,
    TError,
    { id: number; data: UpdateBlogCommand },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateBlog>>,
  TError,
  { id: number; data: UpdateBlogCommand },
  TContext
> => {
  const mutationKey = ["updateBlog"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateBlog>>,
    { id: number; data: UpdateBlogCommand }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateBlog(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateBlogMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateBlog>>
>;
export type UpdateBlogMutationBody = UpdateBlogCommand;
export type UpdateBlogMutationError = ErrorType<void>;

export const useUpdateBlog = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateBlog>>,
      TError,
      { id: number; data: UpdateBlogCommand },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateBlog>>,
  TError,
  { id: number; data: UpdateBlogCommand },
  TContext
> => {
  const mutationOptions = getUpdateBlogMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const deleteBlog = (
  id: number,
  options?: SecondParameter<typeof api>,
) => {
  return api<void>(
    { url: `/api/Admin/V1/Blogs/${id}`, method: "DELETE" },
    options,
  );
};

export const getDeleteBlogMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteBlog>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteBlog>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["deleteBlog"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteBlog>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return deleteBlog(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteBlogMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteBlog>>
>;

export type DeleteBlogMutationError = ErrorType<void>;

export const useDeleteBlog = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteBlog>>,
      TError,
      { id: number },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteBlog>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getDeleteBlogMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const getBlogBySlug2 = (
  slug: string,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<BlogDto>(
    { url: `/api/Admin/V1/Blogs/slug/${slug}`, method: "GET", signal },
    options,
  );
};

export const getGetBlogBySlug2QueryKey = (slug?: string) => {
  return [`/api/Admin/V1/Blogs/slug/${slug}`] as const;
};

export const getGetBlogBySlug2QueryOptions = <
  TData = Awaited<ReturnType<typeof getBlogBySlug2>>,
  TError = ErrorType<void>,
>(
  slug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getBlogBySlug2>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetBlogBySlug2QueryKey(slug);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getBlogBySlug2>>> = ({
    signal,
  }) => getBlogBySlug2(slug, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!slug,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getBlogBySlug2>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetBlogBySlug2QueryResult = NonNullable<
  Awaited<ReturnType<typeof getBlogBySlug2>>
>;
export type GetBlogBySlug2QueryError = ErrorType<void>;

export function useGetBlogBySlug2<
  TData = Awaited<ReturnType<typeof getBlogBySlug2>>,
  TError = ErrorType<void>,
>(
  slug: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getBlogBySlug2>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBlogBySlug2>>,
          TError,
          Awaited<ReturnType<typeof getBlogBySlug2>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetBlogBySlug2<
  TData = Awaited<ReturnType<typeof getBlogBySlug2>>,
  TError = ErrorType<void>,
>(
  slug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getBlogBySlug2>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBlogBySlug2>>,
          TError,
          Awaited<ReturnType<typeof getBlogBySlug2>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetBlogBySlug2<
  TData = Awaited<ReturnType<typeof getBlogBySlug2>>,
  TError = ErrorType<void>,
>(
  slug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getBlogBySlug2>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetBlogBySlug2<
  TData = Awaited<ReturnType<typeof getBlogBySlug2>>,
  TError = ErrorType<void>,
>(
  slug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getBlogBySlug2>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetBlogBySlug2QueryOptions(slug, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
