/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ContactSubmissionDto,
  CreateContactSubmissionCommand,
  GetContactSubmissionsListParams,
  PaginatedListOfContactSubmissionListDto,
} from "../../models";

import { api } from "../../orval-custom-instance";
import type { ErrorType } from "../../orval-custom-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Submits a new contact form entry. The request must include a valid Google reCAPTCHA v3 token.

**Required Fields:**
- fullName: The submitter's full name
- email: Valid email address
- message: The contact message
- type: The type of submission (0 for "message", 1 for "testDrive")
- recaptchaToken: Google reCAPTCHA v3 token
            
**Optional Fields:**
- extraDetails: Additional information or context

**Example Request:**
```json
{
  "fullName": "John Doe",
  "email": "john@example.com",
  "message": "I'm interested in your services",
  "type": 0,
  "extraDetails": "Please contact me about pricing",
  "recaptchaToken": "03AGdBq27..."
}
```
 * @summary Submit a contact form with reCAPTCHA validation
 */
export const createContactSubmission = (
  createContactSubmissionCommand: CreateContactSubmissionCommand,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<number>(
    {
      url: `/api/V1/ContactSubmissions`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createContactSubmissionCommand,
      signal,
    },
    options,
  );
};

export const getCreateContactSubmissionMutationOptions = <
  TError = ErrorType<string>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createContactSubmission>>,
    TError,
    { data: CreateContactSubmissionCommand },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createContactSubmission>>,
  TError,
  { data: CreateContactSubmissionCommand },
  TContext
> => {
  const mutationKey = ["createContactSubmission"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createContactSubmission>>,
    { data: CreateContactSubmissionCommand }
  > = (props) => {
    const { data } = props ?? {};

    return createContactSubmission(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateContactSubmissionMutationResult = NonNullable<
  Awaited<ReturnType<typeof createContactSubmission>>
>;
export type CreateContactSubmissionMutationBody =
  CreateContactSubmissionCommand;
export type CreateContactSubmissionMutationError = ErrorType<string>;

/**
 * @summary Submit a contact form with reCAPTCHA validation
 */
export const useCreateContactSubmission = <
  TError = ErrorType<string>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createContactSubmission>>,
      TError,
      { data: CreateContactSubmissionCommand },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createContactSubmission>>,
  TError,
  { data: CreateContactSubmissionCommand },
  TContext
> => {
  const mutationOptions = getCreateContactSubmissionMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Retrieves a paginated list of contact submissions for admin viewing. Supports filtering and search.
            
**Filters:**
- search: Search across full name, email, message, and extra details
- fullName: Filter by full name (contains)
- email: Filter by email (contains)
- isProcessed: Filter by processed status (true/false)
- type: Filter by submission type (0 for "message", 1 for "testDrive")
            
**Examples:**

- GET /api/Admin/V1/ContactSubmissions?pageNumber=1&pageSize=10
- GET /api/Admin/V1/ContactSubmissions?search=john&isProcessed=false
- GET /api/Admin/V1/ContactSubmissions?email=gmail.com&pageSize=20
- GET /api/Admin/V1/ContactSubmissions?type=1
 * @summary Get paginated list of contact submissions
 */
export const getContactSubmissionsList = (
  params?: GetContactSubmissionsListParams,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<PaginatedListOfContactSubmissionListDto>(
    { url: `/api/Admin/V1/ContactSubmissions`, method: "GET", params, signal },
    options,
  );
};

export const getGetContactSubmissionsListQueryKey = (
  params?: GetContactSubmissionsListParams,
) => {
  return [
    `/api/Admin/V1/ContactSubmissions`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetContactSubmissionsListQueryOptions = <
  TData = Awaited<ReturnType<typeof getContactSubmissionsList>>,
  TError = ErrorType<unknown>,
>(
  params?: GetContactSubmissionsListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getContactSubmissionsList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetContactSubmissionsListQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getContactSubmissionsList>>
  > = ({ signal }) => getContactSubmissionsList(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getContactSubmissionsList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetContactSubmissionsListQueryResult = NonNullable<
  Awaited<ReturnType<typeof getContactSubmissionsList>>
>;
export type GetContactSubmissionsListQueryError = ErrorType<unknown>;

export function useGetContactSubmissionsList<
  TData = Awaited<ReturnType<typeof getContactSubmissionsList>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetContactSubmissionsListParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getContactSubmissionsList>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getContactSubmissionsList>>,
          TError,
          Awaited<ReturnType<typeof getContactSubmissionsList>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetContactSubmissionsList<
  TData = Awaited<ReturnType<typeof getContactSubmissionsList>>,
  TError = ErrorType<unknown>,
>(
  params?: GetContactSubmissionsListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getContactSubmissionsList>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getContactSubmissionsList>>,
          TError,
          Awaited<ReturnType<typeof getContactSubmissionsList>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetContactSubmissionsList<
  TData = Awaited<ReturnType<typeof getContactSubmissionsList>>,
  TError = ErrorType<unknown>,
>(
  params?: GetContactSubmissionsListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getContactSubmissionsList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get paginated list of contact submissions
 */

export function useGetContactSubmissionsList<
  TData = Awaited<ReturnType<typeof getContactSubmissionsList>>,
  TError = ErrorType<unknown>,
>(
  params?: GetContactSubmissionsListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getContactSubmissionsList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetContactSubmissionsListQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get a contact submission by ID
 */
export const getContactSubmission = (
  id: number,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<ContactSubmissionDto>(
    { url: `/api/Admin/V1/ContactSubmissions/${id}`, method: "GET", signal },
    options,
  );
};

export const getGetContactSubmissionQueryKey = (id?: number) => {
  return [`/api/Admin/V1/ContactSubmissions/${id}`] as const;
};

export const getGetContactSubmissionQueryOptions = <
  TData = Awaited<ReturnType<typeof getContactSubmission>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getContactSubmission>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetContactSubmissionQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getContactSubmission>>
  > = ({ signal }) => getContactSubmission(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getContactSubmission>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetContactSubmissionQueryResult = NonNullable<
  Awaited<ReturnType<typeof getContactSubmission>>
>;
export type GetContactSubmissionQueryError = ErrorType<void>;

export function useGetContactSubmission<
  TData = Awaited<ReturnType<typeof getContactSubmission>>,
  TError = ErrorType<void>,
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getContactSubmission>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getContactSubmission>>,
          TError,
          Awaited<ReturnType<typeof getContactSubmission>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetContactSubmission<
  TData = Awaited<ReturnType<typeof getContactSubmission>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getContactSubmission>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getContactSubmission>>,
          TError,
          Awaited<ReturnType<typeof getContactSubmission>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetContactSubmission<
  TData = Awaited<ReturnType<typeof getContactSubmission>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getContactSubmission>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get a contact submission by ID
 */

export function useGetContactSubmission<
  TData = Awaited<ReturnType<typeof getContactSubmission>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getContactSubmission>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetContactSubmissionQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Delete a contact submission
 */
export const deleteContactSubmission = (
  id: number,
  options?: SecondParameter<typeof api>,
) => {
  return api<void>(
    { url: `/api/Admin/V1/ContactSubmissions/${id}`, method: "DELETE" },
    options,
  );
};

export const getDeleteContactSubmissionMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteContactSubmission>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteContactSubmission>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["deleteContactSubmission"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteContactSubmission>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return deleteContactSubmission(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteContactSubmissionMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteContactSubmission>>
>;

export type DeleteContactSubmissionMutationError = ErrorType<void>;

/**
 * @summary Delete a contact submission
 */
export const useDeleteContactSubmission = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteContactSubmission>>,
      TError,
      { id: number },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteContactSubmission>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getDeleteContactSubmissionMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
