/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import type { BlogDtoMetaTagsObject } from "./blogDtoMetaTagsObject";

export interface BlogDto {
  id?: number;
  title?: string;
  slug?: string;
  /** @nullable */
  shortDescription?: string | null;
  /** @nullable */
  fullDescription?: string | null;
  /** @nullable */
  coverImage?: string | null;
  /** @nullable */
  coverImageAbsoluteUrl?: string | null;
  /** @nullable */
  imagesGallery?: string[] | null;
  /** @nullable */
  imagesGalleryAbsoluteUrls?: string[] | null;
  /** @nullable */
  videosGallery?: string[] | null;
  /** @nullable */
  videosGalleryAbsoluteUrls?: string[] | null;
  /** @nullable */
  metaTags?: string | null;
  /** @nullable */
  metaTagsObject?: BlogDtoMetaTagsObject;
  created?: string;
  /** @nullable */
  lastModified?: string | null;
}
