/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import type { BlogListDtoMetaTagsObject } from "./blogListDtoMetaTagsObject";

export interface BlogListDto {
  id?: number;
  title?: string;
  slug?: string;
  /** @nullable */
  shortDescription?: string | null;
  /** @nullable */
  coverImage?: string | null;
  /** @nullable */
  coverImageAbsoluteUrl?: string | null;
  /** @nullable */
  metaTags?: string | null;
  /** @nullable */
  metaTagsObject?: BlogListDtoMetaTagsObject;
  created?: string;
  /** @nullable */
  lastModified?: string | null;
}
