/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import type { CarAttributeType } from "./carAttributeType";

export interface CarAttributeDto {
  id?: number;
  name?: string;
  slug?: string;
  /** @nullable */
  parentId?: number | null;
  /** @nullable */
  image?: string | null;
  /** @nullable */
  icon?: string | null;
  /** @nullable */
  description?: string | null;
  type?: CarAttributeType;
  children?: CarAttributeDto[];
  /** @nullable */
  absoluteImageUrl?: string | null;
  /** @nullable */
  absoluteIconUrl?: string | null;
}
