/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */

export type CarAttributeType =
  (typeof CarAttributeType)[keyof typeof CarAttributeType];

 
export const CarAttributeType = {
  String: 0,
  Number: 1,
  Boolean: 2,
  Color: 3,
  List: 4,
  Title: 5,
} as const;
