/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */

export interface CarDto {
  id?: number;
  stockNumber?: string;
  slug?: string;
  /** @nullable */
  primaryImage?: string | null;
  /** @nullable */
  primaryImageAbsoluteUrl?: string | null;
  /** @nullable */
  price?: number | null;
  /** @nullable */
  salePrice?: number | null;
  /** @nullable */
  manufacturerName?: string | null;
  /** @nullable */
  carModelName?: string | null;
}
