/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import type { CarOptionType } from "./carOptionType";

export interface CarListingOptionDto {
  carOptionId?: number;
  carOptionName?: string;
  carOptionSlug?: string;
  /** @nullable */
  carOptionParentId?: number | null;
  /** @nullable */
  value?: string | null;
  carOptionType?: CarOptionType;
}
