/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */

export interface CarListingAttributeDto {
  id?: number;
  carAttributeId?: number;
  carAttributeName?: string;
  carAttributeSlug?: string;
  /** @nullable */
  carAttributeParentId?: number | null;
  /** @nullable */
  value?: string | null;
  /** @nullable */
  carAttributeDescription?: string | null;
  /** @nullable */
  imageAbsoluteUrl?: string | null;
  /** @nullable */
  iconAbsoluteUrl?: string | null;
}
