/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import type { CarOptionType } from "./carOptionType";

export interface CarOptionDto {
  id?: number;
  name?: string;
  slug?: string;
  /** @nullable */
  parentId?: number | null;
  /** @nullable */
  image?: string | null;
  /** @nullable */
  icon?: string | null;
  /** @nullable */
  description?: string | null;
  type?: CarOptionType;
  children?: CarOptionDto[];
}
