/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import type { ContactSubmissionType } from "./contactSubmissionType";

export interface ContactSubmissionDto {
  id?: number;
  fullName?: string;
  email?: string;
  message?: string;
  type?: ContactSubmissionType;
  /** @nullable */
  extraDetails?: string | null;
  isProcessed?: boolean;
  /** @nullable */
  processedAt?: string | null;
  /** @nullable */
  processedBy?: string | null;
  created?: string;
  lastModified?: string;
}
