/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */

export type ContactSubmissionType =
  (typeof ContactSubmissionType)[keyof typeof ContactSubmissionType];

 
export const ContactSubmissionType = {
  Message: 0,
  TestDrive: 1,
} as const;
