/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import type { ContactSubmissionType } from "./contactSubmissionType";

export interface ContactSubmissionListDto {
  id?: number;
  fullName?: string;
  email?: string;
  message?: string;
  type?: ContactSubmissionType;
  isProcessed?: boolean;
  created?: string;
}
