/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import type { CarModelBulkCreateRequest } from "./carModelBulkCreateRequest";

export interface CreateCarModelsBulkCommand {
  carModels?: CarModelBulkCreateRequest[];
}
