/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import type { CarModelBulkError } from "./carModelBulkError";

export interface CreateCarModelsBulkResponse {
  totalProcessed?: number;
  successfulCount?: number;
  successfulIds?: number[];
  errors?: CarModelBulkError[];
}
