/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */

export interface CreateManufacturerCommand {
  title?: string;
  slug?: string;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  logo?: string | null;
}
