/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */

export interface CreateStaticPageCommand {
  title?: string;
  slug?: string;
  /** @nullable */
  content?: string | null;
  /** @nullable */
  excerpt?: string | null;
  /** @nullable */
  coverImage?: string | null;
  isPublished?: boolean;
  /** @nullable */
  metaTitle?: string | null;
  /** @nullable */
  metaDescription?: string | null;
  /** @nullable */
  imagesGallery?: string[] | null;
  /** @nullable */
  videosGallery?: string[] | null;
  /** @nullable */
  metaTags?: string | null;
}
