/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */

export interface CreateNewsletterSubscriptionCommand {
  /**
   * @minLength 1
   * @maxLength 255
   */
  email: string;
  /**
   * @minLength 1
   * @maxLength 5000
   */
  recaptchaToken: string;
}
