/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import type { ContactSubmissionType } from "./contactSubmissionType";

export interface CreateContactSubmissionCommand {
  /**
   * @minLength 1
   * @maxLength 200
   */
  fullName: string;
  /**
   * @minLength 1
   * @maxLength 255
   */
  email: string;
  /**
   * @minLength 1
   * @maxLength 2000
   */
  message: string;
  type: ContactSubmissionType;
  /**
   * @maxLength 1000
   * @nullable
   */
  extraDetails?: string | null;
  /**
   * @minLength 1
   * @maxLength 5000
   */
  recaptchaToken: string;
}
