/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */

export interface CreateStaticContentCommand {
  title?: string;
  /** @nullable */
  mainImage?: string | null;
  description?: string;
  slug?: string;
}
