/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiAdminV1ImagesParams = {
  pageNumber?: number;
  pageSize?: number;
  /**
   * @nullable
   */
  searchTerm?: string | null;
  /**
   * @nullable
   */
  folderPath?: string | null;
  /**
   * @nullable
   */
  contentType?: string | null;
};
