/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */

export type GetBlogsParams = {
  /**
   * Page number for pagination (default: 1)
   * @nullable
   */
  pageNumber?: number | null;
  /**
   * Number of items per page (default: 10, max: 100)
   * @nullable
   */
  pageSize?: number | null;
  /**
   * Search term to filter blogs
   * @nullable
   */
  search?: string | null;
  /**
   * Field to sort by (created, title, slug, lastModified)
   * @nullable
   */
  sortBy?: string | null;
  /**
   * Sort direction (asc or desc). Default: desc
   * @nullable
   */
  sortDirection?: string | null;
};
