/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import type { GetContactSubmissionsListTypeOneOf } from "./getContactSubmissionsListTypeOneOf";

export type GetContactSubmissionsListParams = {
  /**
   * Page number for pagination (default: 1)
   * @nullable
   */
  pageNumber?: number | null;
  /**
   * Number of items per page (default: 10, max: 100)
   * @nullable
   */
  pageSize?: number | null;
  /**
   * Search term to filter submissions
   * @nullable
   */
  search?: string | null;
  /**
   * Filter by full name
   * @nullable
   */
  fullName?: string | null;
  /**
   * Filter by email address
   * @nullable
   */
  email?: string | null;
  /**
   * Filter by processed status
   * @nullable
   */
  isProcessed?: boolean | null;
  /**
   * Filter by submission type (0 for "message", 1 for "testDrive")
   */
  type?: GetContactSubmissionsListTypeOneOf;
};
