/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */

export type GetCarListings2Params = {
  /**
   * Page number for pagination (default: 1)
   * @nullable
   */
  pageNumber?: number | null;
  /**
   * Number of items per page (default: 10)
   * @nullable
   */
  pageSize?: number | null;
  /**
   * Filter by VIN number (contains match)
   * @nullable
   */
  vinNumber?: string | null;
  /**
   * Filter by sold status (true/false)
   * @nullable
   */
  isSold?: boolean | null;
  /**
   * Filter by special offer status (true/false)
   * @nullable
   */
  isSpecialOffer?: boolean | null;
  /**
   * Search query to filter by multiple terms including stock number
   * @nullable
   */
  searchq?: string | null;
};
