/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */

export type GetCarListingsParams = {
  /**
   * Page number for pagination (default: 1)
   * @nullable
   */
  pageNumber?: number | null;
  /**
   * Number of items per page (default: 10, max: 100)
   * @nullable
   */
  pageSize?: number | null;
  /**
   * Filter by sold status (true/false). Default: null (shows all)
   * @nullable
   */
  isSold?: boolean | null;
  /**
   * Filter by special offer status (true/false)
   * @nullable
   */
  isSpecialOffer?: boolean | null;
  /**
   * Field to sort by (stockNumber, price, salePrice, registrationDate, manufacturerName, carModelName)
   * @nullable
   */
  sortBy?: string | null;
  /**
   * Sort direction (asc or desc). Default: asc
   * @nullable
   */
  sortDirection?: string | null;
  /**
   * Filter by minimum price
   * @nullable
   */
  minPrice?: number | null;
  /**
   * Filter by maximum price
   * @nullable
   */
  maxPrice?: number | null;
  /**
   * Filter by manufacturer ID
   * @nullable
   */
  manufacturerId?: number | null;
  /**
   * Filter by car model ID
   * @nullable
   */
  carModelId?: number | null;
  /**
   * Search query to filter by multiple terms including stock number
   * @nullable
   */
  searchq?: string | null;
};
