/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */

export type GetCarModelsParams = {
  /**
   * @nullable
   */
  pageNumber?: number | null;
  /**
   * @nullable
   */
  pageSize?: number | null;
  /**
   * @nullable
   */
  manufacturerId?: number | null;
};
