/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */

export type GetCarOptionsParams = {
  /**
   * Optional parent ID to get specific option subtree
   * @nullable
   */
  parentId?: number | null;
};
