/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */

export type GetNewsletterSubscriptionsListParams = {
  /**
   * Page number for pagination (default: 1)
   * @nullable
   */
  pageNumber?: number | null;
  /**
   * Number of items per page (default: 10, max: 100)
   * @nullable
   */
  pageSize?: number | null;
  /**
   * Search term to filter subscriptions
   * @nullable
   */
  search?: string | null;
  /**
   * Filter by email address
   * @nullable
   */
  email?: string | null;
  /**
   * Filter by active status
   * @nullable
   */
  isActive?: boolean | null;
};
