/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import type { GetSlidersPlacementOneOf } from "./getSlidersPlacementOneOf";

export type GetSlidersParams = {
  /**
   * Page number for pagination (default: 1)
   * @nullable
   */
  pageNumber?: number | null;
  /**
   * Number of items per page (default: 10)
   * @nullable
   */
  pageSize?: number | null;
  /**
   * Filter by title (contains match)
   * @nullable
   */
  title?: string | null;
  /**
   * Filter by enabled status (true/false)
   * @nullable
   */
  isEnabled?: boolean | null;
  /**
   * Filter by slider placement
   */
  placement?: GetSlidersPlacementOneOf;
};
