/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import type { HttpValidationProblemDetailsAllOfErrors } from "./httpValidationProblemDetailsAllOfErrors";

export type HttpValidationProblemDetailsAllOf = {
  errors?: HttpValidationProblemDetailsAllOfErrors;
  [key: string]: unknown | null;
};
