/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */

export interface ImageDto {
  id?: number;
  originalFileName?: string;
  storedFileName?: string;
  relativeUrl?: string;
  absoluteUrl?: string;
  contentType?: string;
  fileSizeInBytes?: number;
  /** @nullable */
  folderPath?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  altText?: string | null;
  created?: string;
  /** @nullable */
  createdBy?: string | null;
}
