/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */

export interface NewsletterSubscriptionListDto {
  id?: number;
  email?: string;
  isActive?: boolean;
  created?: string;
}
