/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import type { NewsletterSubscriptionListDto } from "./newsletterSubscriptionListDto";

export interface PaginatedListOfNewsletterSubscriptionListDto {
  items?: NewsletterSubscriptionListDto[];
  pageNumber?: number;
  totalPages?: number;
  totalCount?: number;
  hasPreviousPage?: boolean;
  hasNextPage?: boolean;
}
