/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import type { PublicCarListingDtoMetaTagsObject } from "./publicCarListingDtoMetaTagsObject";
import type { CarListingAttributeDto } from "./carListingAttributeDto";
import type { CarListingOptionDto } from "./carListingOptionDto";

export interface PublicCarListingDto {
  id?: number;
  stockNumber?: string;
  slug?: string;
  /** @nullable */
  registrationDate?: string | null;
  /** @nullable */
  primaryImage?: string | null;
  /** @nullable */
  primaryImageAbsoluteUrl?: string | null;
  /** @nullable */
  interiorImages?: string | null;
  absoluteInteriorImages?: string[];
  /** @nullable */
  exteriorImages?: string | null;
  absoluteExteriorImages?: string[];
  /** @nullable */
  videos?: string | null;
  absoluteVideos?: string[];
  /** @nullable */
  price?: number | null;
  /** @nullable */
  salePrice?: number | null;
  isSold?: boolean;
  /** @nullable */
  customPriceLabel?: string | null;
  /** @nullable */
  cardFooterLabel?: string | null;
  isSpecialOffer?: boolean;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  manufacturerId?: number | null;
  /** @nullable */
  manufacturerName?: string | null;
  /** @nullable */
  carModelId?: number | null;
  /** @nullable */
  carModelName?: string | null;
  /** @nullable */
  metaTags?: string | null;
  /** @nullable */
  metaTagsObject?: PublicCarListingDtoMetaTagsObject;
  carListingAttributes?: CarListingAttributeDto[];
  carListingOptions?: CarListingOptionDto[];
}
