/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */

export type SliderPlacement =
  (typeof SliderPlacement)[keyof typeof SliderPlacement];

 
export const SliderPlacement = {
  SpecialOffer: 1,
  Reels: 2,
  HomeSlider1: 3,
} as const;
