/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import type { SliderPlacement } from "./sliderPlacement";
import type { SliderDtoCar } from "./sliderDtoCar";

export interface SliderDto {
  id?: number;
  title?: string;
  /** @nullable */
  shortDescription?: string | null;
  /** @nullable */
  image?: string | null;
  /** @nullable */
  imageAbsoluteUrl?: string | null;
  isEnabled?: boolean;
  /** @nullable */
  bgColor?: string | null;
  /** @nullable */
  video?: string | null;
  /** @nullable */
  videoAbsoluteUrl?: string | null;
  placement?: SliderPlacement;
  /** @nullable */
  carId?: number | null;
  /** @nullable */
  car?: SliderDtoCar;
  created?: string;
  /** @nullable */
  createdBy?: string | null;
  lastModified?: string;
  /** @nullable */
  lastModifiedBy?: string | null;
}
