/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import type { StaticPageListDtoMetaTagsObject } from "./staticPageListDtoMetaTagsObject";

export interface StaticPageListDto {
  id?: number;
  title?: string;
  slug?: string;
  /** @nullable */
  excerpt?: string | null;
  /** @nullable */
  coverImage?: string | null;
  isPublished?: boolean;
  /** @nullable */
  metaTitle?: string | null;
  /** @nullable */
  metaDescription?: string | null;
  /** @nullable */
  metaTags?: string | null;
  /** @nullable */
  metaTagsObject?: StaticPageListDtoMetaTagsObject;
  created?: string;
  /** @nullable */
  lastModified?: string | null;
}
