/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */

export interface StaticContentDto {
  id?: number;
  title?: string;
  /** @nullable */
  mainImage?: string | null;
  /** @nullable */
  mainImageAbsoluteUrl?: string | null;
  description?: string;
  slug?: string;
  created?: string;
  /** @nullable */
  createdBy?: string | null;
  lastModified?: string;
  /** @nullable */
  lastModifiedBy?: string | null;
}
