/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import type { SliderPlacement } from "./sliderPlacement";

export interface UpdateSliderCommand {
  id?: number;
  title?: string;
  /** @nullable */
  shortDescription?: string | null;
  /** @nullable */
  image?: string | null;
  isEnabled?: boolean;
  /** @nullable */
  bgColor?: string | null;
  /** @nullable */
  video?: string | null;
  placement?: SliderPlacement;
  /** @nullable */
  carId?: number | null;
}
