/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateUserCommand {
  id?: string;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  emailConfirmed?: boolean | null;
  /** @nullable */
  role?: string | null;
}
