/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import type { CarAttributeRequest } from "./carAttributeRequest";
import type { CarOptionRequest } from "./carOptionRequest";

export interface UpdateCarListingCommand {
  id?: number;
  /** @nullable */
  slug?: string | null;
  /** @nullable */
  vinNumber?: string | null;
  /** @nullable */
  registrationDate?: string | null;
  /** @nullable */
  primaryImage?: string | null;
  /** @nullable */
  interiorImages?: string | null;
  /** @nullable */
  exteriorImages?: string | null;
  /** @nullable */
  videos?: string | null;
  /** @nullable */
  price?: number | null;
  /** @nullable */
  salePrice?: number | null;
  isSold?: boolean;
  /** @nullable */
  customPriceLabel?: string | null;
  /** @nullable */
  cardFooterLabel?: string | null;
  isSpecialOffer?: boolean;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  manufacturerId?: number | null;
  /** @nullable */
  carModelId?: number | null;
  /** @nullable */
  metaTags?: string | null;
  carAttributes?: CarAttributeRequest[];
  carOptions?: CarOptionRequest[];
}
