/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateBlogCommand {
  id?: number;
  title?: string;
  slug?: string;
  /** @nullable */
  shortDescription?: string | null;
  /** @nullable */
  fullDescription?: string | null;
  /** @nullable */
  coverImage?: string | null;
  /** @nullable */
  imagesGallery?: string[] | null;
  /** @nullable */
  videosGallery?: string[] | null;
  /** @nullable */
  metaTags?: string | null;
}
