/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import type { RoleDto } from "./roleDto";

export interface UserListDto {
  id?: string;
  userName?: string;
  email?: string;
  emailConfirmed?: boolean;
  roles?: RoleDto[];
}
