/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";

import type {
  AdminLoginCommand,
  AdminLoginResponse,
  LoginCommand,
  LoginResponse,
  RegisterUserCommand,
  RegisterUserResponse,
} from "../../models";

import { api } from "../../orval-custom-instance";
import type { ErrorType } from "../../orval-custom-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Registers a new user account. The request must include a valid Google reCAPTCHA v3 token.
            
**Required Fields:**
- email: Valid email address (will be used as username)
- password: Password (minimum 6 characters)
- recaptchaToken: Google reCAPTCHA v3 token
            
**Example Request:**
```json
{
  "email": "user@example.com",
  "password": "password123",
  "recaptchaToken": "03AGdBq27..."
}
```
            
**Success Response:**
```json
{
  "success": true,
  "errors": []
}
```
 * @summary Register a new user with email and password
 */
export const register = (
  registerUserCommand: RegisterUserCommand,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<RegisterUserResponse>(
    {
      url: `/api/V1/Auth/register`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: registerUserCommand,
      signal,
    },
    options,
  );
};

export const getRegisterMutationOptions = <
  TError = ErrorType<RegisterUserResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof register>>,
    TError,
    { data: RegisterUserCommand },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof register>>,
  TError,
  { data: RegisterUserCommand },
  TContext
> => {
  const mutationKey = ["register"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof register>>,
    { data: RegisterUserCommand }
  > = (props) => {
    const { data } = props ?? {};

    return register(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RegisterMutationResult = NonNullable<
  Awaited<ReturnType<typeof register>>
>;
export type RegisterMutationBody = RegisterUserCommand;
export type RegisterMutationError = ErrorType<RegisterUserResponse>;

/**
 * @summary Register a new user with email and password
 */
export const useRegister = <
  TError = ErrorType<RegisterUserResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof register>>,
      TError,
      { data: RegisterUserCommand },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof register>>,
  TError,
  { data: RegisterUserCommand },
  TContext
> => {
  const mutationOptions = getRegisterMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Authenticates a user and returns a JWT token.
            
**Required Fields:**
- userName: Username (email address used during registration)
- password: User password
            
**Example Request:**
```json
{
  "userName": "user@example.com",
  "password": "password123"
}
```
            
**Success Response:**
```json
{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
  "success": true,
  "errors": []
}
```
            
The returned token should be included in the Authorization header for authenticated requests:
```
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
```
 * @summary Login with username (email) and password
 */
export const login = (
  loginCommand: LoginCommand,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<LoginResponse>(
    {
      url: `/api/V1/Auth/login`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: loginCommand,
      signal,
    },
    options,
  );
};

export const getLoginMutationOptions = <
  TError = ErrorType<LoginResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof login>>,
    TError,
    { data: LoginCommand },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof login>>,
  TError,
  { data: LoginCommand },
  TContext
> => {
  const mutationKey = ["login"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof login>>,
    { data: LoginCommand }
  > = (props) => {
    const { data } = props ?? {};

    return login(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LoginMutationResult = NonNullable<
  Awaited<ReturnType<typeof login>>
>;
export type LoginMutationBody = LoginCommand;
export type LoginMutationError = ErrorType<LoginResponse>;

/**
 * @summary Login with username (email) and password
 */
export const useLogin = <TError = ErrorType<LoginResponse>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof login>>,
      TError,
      { data: LoginCommand },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof login>>,
  TError,
  { data: LoginCommand },
  TContext
> => {
  const mutationOptions = getLoginMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const adminLogin = (
  adminLoginCommand: AdminLoginCommand,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<AdminLoginResponse>(
    {
      url: `/api/Admin/V1/Auth/login`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: adminLoginCommand,
      signal,
    },
    options,
  );
};

export const getAdminLoginMutationOptions = <
  TError = ErrorType<AdminLoginResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminLogin>>,
    TError,
    { data: AdminLoginCommand },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminLogin>>,
  TError,
  { data: AdminLoginCommand },
  TContext
> => {
  const mutationKey = ["adminLogin"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminLogin>>,
    { data: AdminLoginCommand }
  > = (props) => {
    const { data } = props ?? {};

    return adminLogin(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdminLoginMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminLogin>>
>;
export type AdminLoginMutationBody = AdminLoginCommand;
export type AdminLoginMutationError = ErrorType<AdminLoginResponse>;

export const useAdminLogin = <
  TError = ErrorType<AdminLoginResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminLogin>>,
      TError,
      { data: AdminLoginCommand },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof adminLogin>>,
  TError,
  { data: AdminLoginCommand },
  TContext
> => {
  const mutationOptions = getAdminLoginMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
