/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CreateNewsletterSubscriptionCommand,
  GetNewsletterSubscriptionsListParams,
  NewsletterSubscriptionDto,
  PaginatedListOfNewsletterSubscriptionListDto,
} from "../../models";

import { api } from "../../orval-custom-instance";
import type { ErrorType } from "../../orval-custom-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Subscribes an email to the newsletter. The request must include a valid Google reCAPTCHA v3 token.
If the email is already subscribed, the existing subscription ID is returned without error.
            
**Required Fields:**
- email: Valid email address to subscribe
- recaptchaToken: Google reCAPTCHA v3 token
            
**Example Request:**
```json
{
  "email": "john@example.com",
  "recaptchaToken": "03AGdBq27..."
}
```
 * @summary Subscribe to newsletter with reCAPTCHA validation
 */
export const createNewsletterSubscription = (
  createNewsletterSubscriptionCommand: CreateNewsletterSubscriptionCommand,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<number>(
    {
      url: `/api/V1/NewsletterSubscriptions`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createNewsletterSubscriptionCommand,
      signal,
    },
    options,
  );
};

export const getCreateNewsletterSubscriptionMutationOptions = <
  TError = ErrorType<string>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createNewsletterSubscription>>,
    TError,
    { data: CreateNewsletterSubscriptionCommand },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createNewsletterSubscription>>,
  TError,
  { data: CreateNewsletterSubscriptionCommand },
  TContext
> => {
  const mutationKey = ["createNewsletterSubscription"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createNewsletterSubscription>>,
    { data: CreateNewsletterSubscriptionCommand }
  > = (props) => {
    const { data } = props ?? {};

    return createNewsletterSubscription(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateNewsletterSubscriptionMutationResult = NonNullable<
  Awaited<ReturnType<typeof createNewsletterSubscription>>
>;
export type CreateNewsletterSubscriptionMutationBody =
  CreateNewsletterSubscriptionCommand;
export type CreateNewsletterSubscriptionMutationError = ErrorType<string>;

/**
 * @summary Subscribe to newsletter with reCAPTCHA validation
 */
export const useCreateNewsletterSubscription = <
  TError = ErrorType<string>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createNewsletterSubscription>>,
      TError,
      { data: CreateNewsletterSubscriptionCommand },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createNewsletterSubscription>>,
  TError,
  { data: CreateNewsletterSubscriptionCommand },
  TContext
> => {
  const mutationOptions =
    getCreateNewsletterSubscriptionMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Retrieves a paginated list of newsletter subscriptions for admin viewing. Supports filtering and search.
            
**Filters:**
- search: Search across email addresses
- email: Filter by email (contains)
- isActive: Filter by active status (true/false)
            
**Examples:**

- GET /api/Admin/V1/NewsletterSubscriptions?pageNumber=1&pageSize=10
- GET /api/Admin/V1/NewsletterSubscriptions?search=john&isActive=true
- GET /api/Admin/V1/NewsletterSubscriptions?email=gmail.com&pageSize=20
 * @summary Get paginated list of newsletter subscriptions
 */
export const getNewsletterSubscriptionsList = (
  params?: GetNewsletterSubscriptionsListParams,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<PaginatedListOfNewsletterSubscriptionListDto>(
    {
      url: `/api/Admin/V1/NewsletterSubscriptions`,
      method: "GET",
      params,
      signal,
    },
    options,
  );
};

export const getGetNewsletterSubscriptionsListQueryKey = (
  params?: GetNewsletterSubscriptionsListParams,
) => {
  return [
    `/api/Admin/V1/NewsletterSubscriptions`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetNewsletterSubscriptionsListQueryOptions = <
  TData = Awaited<ReturnType<typeof getNewsletterSubscriptionsList>>,
  TError = ErrorType<unknown>,
>(
  params?: GetNewsletterSubscriptionsListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getNewsletterSubscriptionsList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetNewsletterSubscriptionsListQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getNewsletterSubscriptionsList>>
  > = ({ signal }) =>
    getNewsletterSubscriptionsList(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getNewsletterSubscriptionsList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetNewsletterSubscriptionsListQueryResult = NonNullable<
  Awaited<ReturnType<typeof getNewsletterSubscriptionsList>>
>;
export type GetNewsletterSubscriptionsListQueryError = ErrorType<unknown>;

export function useGetNewsletterSubscriptionsList<
  TData = Awaited<ReturnType<typeof getNewsletterSubscriptionsList>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetNewsletterSubscriptionsListParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getNewsletterSubscriptionsList>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNewsletterSubscriptionsList>>,
          TError,
          Awaited<ReturnType<typeof getNewsletterSubscriptionsList>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetNewsletterSubscriptionsList<
  TData = Awaited<ReturnType<typeof getNewsletterSubscriptionsList>>,
  TError = ErrorType<unknown>,
>(
  params?: GetNewsletterSubscriptionsListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getNewsletterSubscriptionsList>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNewsletterSubscriptionsList>>,
          TError,
          Awaited<ReturnType<typeof getNewsletterSubscriptionsList>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetNewsletterSubscriptionsList<
  TData = Awaited<ReturnType<typeof getNewsletterSubscriptionsList>>,
  TError = ErrorType<unknown>,
>(
  params?: GetNewsletterSubscriptionsListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getNewsletterSubscriptionsList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get paginated list of newsletter subscriptions
 */

export function useGetNewsletterSubscriptionsList<
  TData = Awaited<ReturnType<typeof getNewsletterSubscriptionsList>>,
  TError = ErrorType<unknown>,
>(
  params?: GetNewsletterSubscriptionsListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getNewsletterSubscriptionsList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetNewsletterSubscriptionsListQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get a newsletter subscription by ID
 */
export const getNewsletterSubscription = (
  id: number,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<NewsletterSubscriptionDto>(
    {
      url: `/api/Admin/V1/NewsletterSubscriptions/${id}`,
      method: "GET",
      signal,
    },
    options,
  );
};

export const getGetNewsletterSubscriptionQueryKey = (id?: number) => {
  return [`/api/Admin/V1/NewsletterSubscriptions/${id}`] as const;
};

export const getGetNewsletterSubscriptionQueryOptions = <
  TData = Awaited<ReturnType<typeof getNewsletterSubscription>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getNewsletterSubscription>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetNewsletterSubscriptionQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getNewsletterSubscription>>
  > = ({ signal }) => getNewsletterSubscription(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getNewsletterSubscription>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetNewsletterSubscriptionQueryResult = NonNullable<
  Awaited<ReturnType<typeof getNewsletterSubscription>>
>;
export type GetNewsletterSubscriptionQueryError = ErrorType<void>;

export function useGetNewsletterSubscription<
  TData = Awaited<ReturnType<typeof getNewsletterSubscription>>,
  TError = ErrorType<void>,
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getNewsletterSubscription>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNewsletterSubscription>>,
          TError,
          Awaited<ReturnType<typeof getNewsletterSubscription>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetNewsletterSubscription<
  TData = Awaited<ReturnType<typeof getNewsletterSubscription>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getNewsletterSubscription>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNewsletterSubscription>>,
          TError,
          Awaited<ReturnType<typeof getNewsletterSubscription>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetNewsletterSubscription<
  TData = Awaited<ReturnType<typeof getNewsletterSubscription>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getNewsletterSubscription>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get a newsletter subscription by ID
 */

export function useGetNewsletterSubscription<
  TData = Awaited<ReturnType<typeof getNewsletterSubscription>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getNewsletterSubscription>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetNewsletterSubscriptionQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Delete a newsletter subscription
 */
export const deleteNewsletterSubscription = (
  id: number,
  options?: SecondParameter<typeof api>,
) => {
  return api<void>(
    { url: `/api/Admin/V1/NewsletterSubscriptions/${id}`, method: "DELETE" },
    options,
  );
};

export const getDeleteNewsletterSubscriptionMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteNewsletterSubscription>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteNewsletterSubscription>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["deleteNewsletterSubscription"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteNewsletterSubscription>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return deleteNewsletterSubscription(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteNewsletterSubscriptionMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteNewsletterSubscription>>
>;

export type DeleteNewsletterSubscriptionMutationError = ErrorType<void>;

/**
 * @summary Delete a newsletter subscription
 */
export const useDeleteNewsletterSubscription = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteNewsletterSubscription>>,
      TError,
      { id: number },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteNewsletterSubscription>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions =
    getDeleteNewsletterSubscriptionMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
