/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CarModelDto,
  CreateCarModelCommand,
  CreateCarModelsBulkCommand,
  CreateCarModelsBulkResponse,
  GetCarModelsParams,
  HttpValidationProblemDetails,
  PaginatedListOfCarModelDto,
  UpdateCarModelCommand,
} from "../../models";

import { api } from "../../orval-custom-instance";
import type { ErrorType } from "../../orval-custom-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getCarModels = (
  params?: GetCarModelsParams,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<PaginatedListOfCarModelDto>(
    { url: `/api/Admin/V1/CarModels`, method: "GET", params, signal },
    options,
  );
};

export const getGetCarModelsQueryKey = (params?: GetCarModelsParams) => {
  return [`/api/Admin/V1/CarModels`, ...(params ? [params] : [])] as const;
};

export const getGetCarModelsQueryOptions = <
  TData = Awaited<ReturnType<typeof getCarModels>>,
  TError = ErrorType<unknown>,
>(
  params?: GetCarModelsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCarModels>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCarModelsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCarModels>>> = ({
    signal,
  }) => getCarModels(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCarModels>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCarModelsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCarModels>>
>;
export type GetCarModelsQueryError = ErrorType<unknown>;

export function useGetCarModels<
  TData = Awaited<ReturnType<typeof getCarModels>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetCarModelsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCarModels>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCarModels>>,
          TError,
          Awaited<ReturnType<typeof getCarModels>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCarModels<
  TData = Awaited<ReturnType<typeof getCarModels>>,
  TError = ErrorType<unknown>,
>(
  params?: GetCarModelsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCarModels>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCarModels>>,
          TError,
          Awaited<ReturnType<typeof getCarModels>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCarModels<
  TData = Awaited<ReturnType<typeof getCarModels>>,
  TError = ErrorType<unknown>,
>(
  params?: GetCarModelsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCarModels>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetCarModels<
  TData = Awaited<ReturnType<typeof getCarModels>>,
  TError = ErrorType<unknown>,
>(
  params?: GetCarModelsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCarModels>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetCarModelsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const createCarModel = (
  createCarModelCommand: CreateCarModelCommand,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<number>(
    {
      url: `/api/Admin/V1/CarModels`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createCarModelCommand,
      signal,
    },
    options,
  );
};

export const getCreateCarModelMutationOptions = <
  TError = ErrorType<HttpValidationProblemDetails>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createCarModel>>,
    TError,
    { data: CreateCarModelCommand },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createCarModel>>,
  TError,
  { data: CreateCarModelCommand },
  TContext
> => {
  const mutationKey = ["createCarModel"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createCarModel>>,
    { data: CreateCarModelCommand }
  > = (props) => {
    const { data } = props ?? {};

    return createCarModel(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateCarModelMutationResult = NonNullable<
  Awaited<ReturnType<typeof createCarModel>>
>;
export type CreateCarModelMutationBody = CreateCarModelCommand;
export type CreateCarModelMutationError =
  ErrorType<HttpValidationProblemDetails>;

export const useCreateCarModel = <
  TError = ErrorType<HttpValidationProblemDetails>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createCarModel>>,
      TError,
      { data: CreateCarModelCommand },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createCarModel>>,
  TError,
  { data: CreateCarModelCommand },
  TContext
> => {
  const mutationOptions = getCreateCarModelMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const getCarModelById = (
  id: number,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<CarModelDto>(
    { url: `/api/Admin/V1/CarModels/${id}`, method: "GET", signal },
    options,
  );
};

export const getGetCarModelByIdQueryKey = (id?: number) => {
  return [`/api/Admin/V1/CarModels/${id}`] as const;
};

export const getGetCarModelByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getCarModelById>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCarModelById>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCarModelByIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCarModelById>>> = ({
    signal,
  }) => getCarModelById(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getCarModelById>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCarModelByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCarModelById>>
>;
export type GetCarModelByIdQueryError = ErrorType<void>;

export function useGetCarModelById<
  TData = Awaited<ReturnType<typeof getCarModelById>>,
  TError = ErrorType<void>,
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCarModelById>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCarModelById>>,
          TError,
          Awaited<ReturnType<typeof getCarModelById>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCarModelById<
  TData = Awaited<ReturnType<typeof getCarModelById>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCarModelById>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCarModelById>>,
          TError,
          Awaited<ReturnType<typeof getCarModelById>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCarModelById<
  TData = Awaited<ReturnType<typeof getCarModelById>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCarModelById>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetCarModelById<
  TData = Awaited<ReturnType<typeof getCarModelById>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCarModelById>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetCarModelByIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const updateCarModel = (
  id: number,
  updateCarModelCommand: UpdateCarModelCommand,
  options?: SecondParameter<typeof api>,
) => {
  return api<void>(
    {
      url: `/api/Admin/V1/CarModels/${id}`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: updateCarModelCommand,
    },
    options,
  );
};

export const getUpdateCarModelMutationOptions = <
  TError = ErrorType<HttpValidationProblemDetails | void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateCarModel>>,
    TError,
    { id: number; data: UpdateCarModelCommand },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateCarModel>>,
  TError,
  { id: number; data: UpdateCarModelCommand },
  TContext
> => {
  const mutationKey = ["updateCarModel"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateCarModel>>,
    { id: number; data: UpdateCarModelCommand }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateCarModel(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateCarModelMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateCarModel>>
>;
export type UpdateCarModelMutationBody = UpdateCarModelCommand;
export type UpdateCarModelMutationError =
  ErrorType<HttpValidationProblemDetails | void>;

export const useUpdateCarModel = <
  TError = ErrorType<HttpValidationProblemDetails | void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateCarModel>>,
      TError,
      { id: number; data: UpdateCarModelCommand },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateCarModel>>,
  TError,
  { id: number; data: UpdateCarModelCommand },
  TContext
> => {
  const mutationOptions = getUpdateCarModelMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const deleteCarModel = (
  id: number,
  options?: SecondParameter<typeof api>,
) => {
  return api<void>(
    { url: `/api/Admin/V1/CarModels/${id}`, method: "DELETE" },
    options,
  );
};

export const getDeleteCarModelMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteCarModel>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteCarModel>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["deleteCarModel"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteCarModel>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return deleteCarModel(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteCarModelMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteCarModel>>
>;

export type DeleteCarModelMutationError = ErrorType<void>;

export const useDeleteCarModel = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteCarModel>>,
      TError,
      { id: number },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteCarModel>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getDeleteCarModelMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const getCarModelsByManufacturer = (
  manufacturerId: number,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<CarModelDto[]>(
    {
      url: `/api/Admin/V1/CarModels/manufacturer/${manufacturerId}`,
      method: "GET",
      signal,
    },
    options,
  );
};

export const getGetCarModelsByManufacturerQueryKey = (
  manufacturerId?: number,
) => {
  return [`/api/Admin/V1/CarModels/manufacturer/${manufacturerId}`] as const;
};

export const getGetCarModelsByManufacturerQueryOptions = <
  TData = Awaited<ReturnType<typeof getCarModelsByManufacturer>>,
  TError = ErrorType<unknown>,
>(
  manufacturerId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCarModelsByManufacturer>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetCarModelsByManufacturerQueryKey(manufacturerId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getCarModelsByManufacturer>>
  > = ({ signal }) =>
    getCarModelsByManufacturer(manufacturerId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!manufacturerId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getCarModelsByManufacturer>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCarModelsByManufacturerQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCarModelsByManufacturer>>
>;
export type GetCarModelsByManufacturerQueryError = ErrorType<unknown>;

export function useGetCarModelsByManufacturer<
  TData = Awaited<ReturnType<typeof getCarModelsByManufacturer>>,
  TError = ErrorType<unknown>,
>(
  manufacturerId: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCarModelsByManufacturer>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCarModelsByManufacturer>>,
          TError,
          Awaited<ReturnType<typeof getCarModelsByManufacturer>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCarModelsByManufacturer<
  TData = Awaited<ReturnType<typeof getCarModelsByManufacturer>>,
  TError = ErrorType<unknown>,
>(
  manufacturerId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCarModelsByManufacturer>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCarModelsByManufacturer>>,
          TError,
          Awaited<ReturnType<typeof getCarModelsByManufacturer>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCarModelsByManufacturer<
  TData = Awaited<ReturnType<typeof getCarModelsByManufacturer>>,
  TError = ErrorType<unknown>,
>(
  manufacturerId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCarModelsByManufacturer>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetCarModelsByManufacturer<
  TData = Awaited<ReturnType<typeof getCarModelsByManufacturer>>,
  TError = ErrorType<unknown>,
>(
  manufacturerId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCarModelsByManufacturer>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetCarModelsByManufacturerQueryOptions(
    manufacturerId,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const createCarModelsBulk = (
  createCarModelsBulkCommand: CreateCarModelsBulkCommand,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<CreateCarModelsBulkResponse>(
    {
      url: `/api/Admin/V1/CarModels/bulk`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createCarModelsBulkCommand,
      signal,
    },
    options,
  );
};

export const getCreateCarModelsBulkMutationOptions = <
  TError = ErrorType<HttpValidationProblemDetails>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createCarModelsBulk>>,
    TError,
    { data: CreateCarModelsBulkCommand },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createCarModelsBulk>>,
  TError,
  { data: CreateCarModelsBulkCommand },
  TContext
> => {
  const mutationKey = ["createCarModelsBulk"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createCarModelsBulk>>,
    { data: CreateCarModelsBulkCommand }
  > = (props) => {
    const { data } = props ?? {};

    return createCarModelsBulk(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateCarModelsBulkMutationResult = NonNullable<
  Awaited<ReturnType<typeof createCarModelsBulk>>
>;
export type CreateCarModelsBulkMutationBody = CreateCarModelsBulkCommand;
export type CreateCarModelsBulkMutationError =
  ErrorType<HttpValidationProblemDetails>;

export const useCreateCarModelsBulk = <
  TError = ErrorType<HttpValidationProblemDetails>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createCarModelsBulk>>,
      TError,
      { data: CreateCarModelsBulkCommand },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createCarModelsBulk>>,
  TError,
  { data: CreateCarModelsBulkCommand },
  TContext
> => {
  const mutationOptions = getCreateCarModelsBulkMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
