/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CreateStaticPageCommand,
  GetStaticPagesListParams,
  PaginatedListOfStaticPageListDto,
  StaticPageDto,
  UpdateStaticPageCommand,
} from "../../models";

import { api } from "../../orval-custom-instance";
import type { ErrorType } from "../../orval-custom-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getStaticPagesList = (
  params?: GetStaticPagesListParams,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<PaginatedListOfStaticPageListDto>(
    { url: `/api/Admin/V1/StaticPages`, method: "GET", params, signal },
    options,
  );
};

export const getGetStaticPagesListQueryKey = (
  params?: GetStaticPagesListParams,
) => {
  return [`/api/Admin/V1/StaticPages`, ...(params ? [params] : [])] as const;
};

export const getGetStaticPagesListQueryOptions = <
  TData = Awaited<ReturnType<typeof getStaticPagesList>>,
  TError = ErrorType<unknown>,
>(
  params?: GetStaticPagesListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getStaticPagesList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetStaticPagesListQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getStaticPagesList>>
  > = ({ signal }) => getStaticPagesList(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getStaticPagesList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetStaticPagesListQueryResult = NonNullable<
  Awaited<ReturnType<typeof getStaticPagesList>>
>;
export type GetStaticPagesListQueryError = ErrorType<unknown>;

export function useGetStaticPagesList<
  TData = Awaited<ReturnType<typeof getStaticPagesList>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetStaticPagesListParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getStaticPagesList>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStaticPagesList>>,
          TError,
          Awaited<ReturnType<typeof getStaticPagesList>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetStaticPagesList<
  TData = Awaited<ReturnType<typeof getStaticPagesList>>,
  TError = ErrorType<unknown>,
>(
  params?: GetStaticPagesListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getStaticPagesList>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStaticPagesList>>,
          TError,
          Awaited<ReturnType<typeof getStaticPagesList>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetStaticPagesList<
  TData = Awaited<ReturnType<typeof getStaticPagesList>>,
  TError = ErrorType<unknown>,
>(
  params?: GetStaticPagesListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getStaticPagesList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetStaticPagesList<
  TData = Awaited<ReturnType<typeof getStaticPagesList>>,
  TError = ErrorType<unknown>,
>(
  params?: GetStaticPagesListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getStaticPagesList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetStaticPagesListQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const createStaticPage = (
  createStaticPageCommand: CreateStaticPageCommand,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<number>(
    {
      url: `/api/Admin/V1/StaticPages`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createStaticPageCommand,
      signal,
    },
    options,
  );
};

export const getCreateStaticPageMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createStaticPage>>,
    TError,
    { data: CreateStaticPageCommand },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createStaticPage>>,
  TError,
  { data: CreateStaticPageCommand },
  TContext
> => {
  const mutationKey = ["createStaticPage"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createStaticPage>>,
    { data: CreateStaticPageCommand }
  > = (props) => {
    const { data } = props ?? {};

    return createStaticPage(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateStaticPageMutationResult = NonNullable<
  Awaited<ReturnType<typeof createStaticPage>>
>;
export type CreateStaticPageMutationBody = CreateStaticPageCommand;
export type CreateStaticPageMutationError = ErrorType<unknown>;

export const useCreateStaticPage = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createStaticPage>>,
      TError,
      { data: CreateStaticPageCommand },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createStaticPage>>,
  TError,
  { data: CreateStaticPageCommand },
  TContext
> => {
  const mutationOptions = getCreateStaticPageMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const getStaticPage = (
  id: number,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<StaticPageDto>(
    { url: `/api/Admin/V1/StaticPages/${id}`, method: "GET", signal },
    options,
  );
};

export const getGetStaticPageQueryKey = (id?: number) => {
  return [`/api/Admin/V1/StaticPages/${id}`] as const;
};

export const getGetStaticPageQueryOptions = <
  TData = Awaited<ReturnType<typeof getStaticPage>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getStaticPage>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetStaticPageQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getStaticPage>>> = ({
    signal,
  }) => getStaticPage(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getStaticPage>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetStaticPageQueryResult = NonNullable<
  Awaited<ReturnType<typeof getStaticPage>>
>;
export type GetStaticPageQueryError = ErrorType<void>;

export function useGetStaticPage<
  TData = Awaited<ReturnType<typeof getStaticPage>>,
  TError = ErrorType<void>,
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getStaticPage>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStaticPage>>,
          TError,
          Awaited<ReturnType<typeof getStaticPage>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetStaticPage<
  TData = Awaited<ReturnType<typeof getStaticPage>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getStaticPage>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStaticPage>>,
          TError,
          Awaited<ReturnType<typeof getStaticPage>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetStaticPage<
  TData = Awaited<ReturnType<typeof getStaticPage>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getStaticPage>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetStaticPage<
  TData = Awaited<ReturnType<typeof getStaticPage>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getStaticPage>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetStaticPageQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const updateStaticPage = (
  id: number,
  updateStaticPageCommand: UpdateStaticPageCommand,
  options?: SecondParameter<typeof api>,
) => {
  return api<void>(
    {
      url: `/api/Admin/V1/StaticPages/${id}`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: updateStaticPageCommand,
    },
    options,
  );
};

export const getUpdateStaticPageMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateStaticPage>>,
    TError,
    { id: number; data: UpdateStaticPageCommand },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateStaticPage>>,
  TError,
  { id: number; data: UpdateStaticPageCommand },
  TContext
> => {
  const mutationKey = ["updateStaticPage"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateStaticPage>>,
    { id: number; data: UpdateStaticPageCommand }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateStaticPage(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateStaticPageMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateStaticPage>>
>;
export type UpdateStaticPageMutationBody = UpdateStaticPageCommand;
export type UpdateStaticPageMutationError = ErrorType<void>;

export const useUpdateStaticPage = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateStaticPage>>,
      TError,
      { id: number; data: UpdateStaticPageCommand },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateStaticPage>>,
  TError,
  { id: number; data: UpdateStaticPageCommand },
  TContext
> => {
  const mutationOptions = getUpdateStaticPageMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const deleteStaticPage = (
  id: number,
  options?: SecondParameter<typeof api>,
) => {
  return api<void>(
    { url: `/api/Admin/V1/StaticPages/${id}`, method: "DELETE" },
    options,
  );
};

export const getDeleteStaticPageMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteStaticPage>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteStaticPage>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["deleteStaticPage"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteStaticPage>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return deleteStaticPage(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteStaticPageMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteStaticPage>>
>;

export type DeleteStaticPageMutationError = ErrorType<void>;

export const useDeleteStaticPage = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteStaticPage>>,
      TError,
      { id: number },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteStaticPage>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getDeleteStaticPageMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const getStaticPageBySlug = (
  slug: string,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<StaticPageDto>(
    { url: `/api/Admin/V1/StaticPages/slug/${slug}`, method: "GET", signal },
    options,
  );
};

export const getGetStaticPageBySlugQueryKey = (slug?: string) => {
  return [`/api/Admin/V1/StaticPages/slug/${slug}`] as const;
};

export const getGetStaticPageBySlugQueryOptions = <
  TData = Awaited<ReturnType<typeof getStaticPageBySlug>>,
  TError = ErrorType<void>,
>(
  slug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getStaticPageBySlug>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetStaticPageBySlugQueryKey(slug);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getStaticPageBySlug>>
  > = ({ signal }) => getStaticPageBySlug(slug, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!slug,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getStaticPageBySlug>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetStaticPageBySlugQueryResult = NonNullable<
  Awaited<ReturnType<typeof getStaticPageBySlug>>
>;
export type GetStaticPageBySlugQueryError = ErrorType<void>;

export function useGetStaticPageBySlug<
  TData = Awaited<ReturnType<typeof getStaticPageBySlug>>,
  TError = ErrorType<void>,
>(
  slug: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getStaticPageBySlug>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStaticPageBySlug>>,
          TError,
          Awaited<ReturnType<typeof getStaticPageBySlug>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetStaticPageBySlug<
  TData = Awaited<ReturnType<typeof getStaticPageBySlug>>,
  TError = ErrorType<void>,
>(
  slug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getStaticPageBySlug>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStaticPageBySlug>>,
          TError,
          Awaited<ReturnType<typeof getStaticPageBySlug>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetStaticPageBySlug<
  TData = Awaited<ReturnType<typeof getStaticPageBySlug>>,
  TError = ErrorType<void>,
>(
  slug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getStaticPageBySlug>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetStaticPageBySlug<
  TData = Awaited<ReturnType<typeof getStaticPageBySlug>>,
  TError = ErrorType<void>,
>(
  slug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getStaticPageBySlug>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetStaticPageBySlugQueryOptions(slug, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
