/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CarAttributeDto,
  CreateCarAttributeCommand,
  GetCarAttributes2Params,
  GetCarAttributesParams,
  UpdateCarAttributeCommand,
} from "../../models";

import { api } from "../../orval-custom-instance";
import type { ErrorType } from "../../orval-custom-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Retrieves a hierarchical list of car attributes available for filtering and browsing car listings.
Attributes are organized in a tree structure with parent-child relationships.
            
**Attribute Types:**
- String (0): Text values like brand names, models
- Number (1): Numeric values like year, mileage
- Boolean (2): True/False values
- Color (3): Color values with potential hex codes
- List (4): Predefined list of options
            
**Usage Examples:**
- GET /api/V1/CarAttributes (returns all root attributes with their children)
- GET /api/V1/CarAttributes?parentId=1 (returns specific attribute and its children)
            
**Common Use Cases:**
- Building filter dropdowns for car search
- Displaying available car features and specifications
- Creating faceted search interfaces
 * @summary Get car attributes hierarchy for public browsing
 */
export const getCarAttributes = (
  params?: GetCarAttributesParams,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<CarAttributeDto[]>(
    { url: `/api/V1/CarAttributes`, method: "GET", params, signal },
    options,
  );
};

export const getGetCarAttributesQueryKey = (
  params?: GetCarAttributesParams,
) => {
  return [`/api/V1/CarAttributes`, ...(params ? [params] : [])] as const;
};

export const getGetCarAttributesQueryOptions = <
  TData = Awaited<ReturnType<typeof getCarAttributes>>,
  TError = ErrorType<unknown>,
>(
  params?: GetCarAttributesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCarAttributes>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetCarAttributesQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getCarAttributes>>
  > = ({ signal }) => getCarAttributes(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCarAttributes>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCarAttributesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCarAttributes>>
>;
export type GetCarAttributesQueryError = ErrorType<unknown>;

export function useGetCarAttributes<
  TData = Awaited<ReturnType<typeof getCarAttributes>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetCarAttributesParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCarAttributes>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCarAttributes>>,
          TError,
          Awaited<ReturnType<typeof getCarAttributes>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCarAttributes<
  TData = Awaited<ReturnType<typeof getCarAttributes>>,
  TError = ErrorType<unknown>,
>(
  params?: GetCarAttributesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCarAttributes>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCarAttributes>>,
          TError,
          Awaited<ReturnType<typeof getCarAttributes>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCarAttributes<
  TData = Awaited<ReturnType<typeof getCarAttributes>>,
  TError = ErrorType<unknown>,
>(
  params?: GetCarAttributesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCarAttributes>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get car attributes hierarchy for public browsing
 */

export function useGetCarAttributes<
  TData = Awaited<ReturnType<typeof getCarAttributes>>,
  TError = ErrorType<unknown>,
>(
  params?: GetCarAttributesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCarAttributes>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetCarAttributesQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getCarAttributes2 = (
  params?: GetCarAttributes2Params,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<CarAttributeDto[]>(
    { url: `/api/Admin/V1/CarAttributes`, method: "GET", params, signal },
    options,
  );
};

export const getGetCarAttributes2QueryKey = (
  params?: GetCarAttributes2Params,
) => {
  return [`/api/Admin/V1/CarAttributes`, ...(params ? [params] : [])] as const;
};

export const getGetCarAttributes2QueryOptions = <
  TData = Awaited<ReturnType<typeof getCarAttributes2>>,
  TError = ErrorType<unknown>,
>(
  params?: GetCarAttributes2Params,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCarAttributes2>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetCarAttributes2QueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getCarAttributes2>>
  > = ({ signal }) => getCarAttributes2(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCarAttributes2>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCarAttributes2QueryResult = NonNullable<
  Awaited<ReturnType<typeof getCarAttributes2>>
>;
export type GetCarAttributes2QueryError = ErrorType<unknown>;

export function useGetCarAttributes2<
  TData = Awaited<ReturnType<typeof getCarAttributes2>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetCarAttributes2Params,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCarAttributes2>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCarAttributes2>>,
          TError,
          Awaited<ReturnType<typeof getCarAttributes2>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCarAttributes2<
  TData = Awaited<ReturnType<typeof getCarAttributes2>>,
  TError = ErrorType<unknown>,
>(
  params?: GetCarAttributes2Params,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCarAttributes2>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCarAttributes2>>,
          TError,
          Awaited<ReturnType<typeof getCarAttributes2>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCarAttributes2<
  TData = Awaited<ReturnType<typeof getCarAttributes2>>,
  TError = ErrorType<unknown>,
>(
  params?: GetCarAttributes2Params,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCarAttributes2>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetCarAttributes2<
  TData = Awaited<ReturnType<typeof getCarAttributes2>>,
  TError = ErrorType<unknown>,
>(
  params?: GetCarAttributes2Params,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCarAttributes2>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetCarAttributes2QueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const createCarAttribute = (
  createCarAttributeCommand: CreateCarAttributeCommand,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<number>(
    {
      url: `/api/Admin/V1/CarAttributes`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createCarAttributeCommand,
      signal,
    },
    options,
  );
};

export const getCreateCarAttributeMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createCarAttribute>>,
    TError,
    { data: CreateCarAttributeCommand },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createCarAttribute>>,
  TError,
  { data: CreateCarAttributeCommand },
  TContext
> => {
  const mutationKey = ["createCarAttribute"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createCarAttribute>>,
    { data: CreateCarAttributeCommand }
  > = (props) => {
    const { data } = props ?? {};

    return createCarAttribute(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateCarAttributeMutationResult = NonNullable<
  Awaited<ReturnType<typeof createCarAttribute>>
>;
export type CreateCarAttributeMutationBody = CreateCarAttributeCommand;
export type CreateCarAttributeMutationError = ErrorType<unknown>;

export const useCreateCarAttribute = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createCarAttribute>>,
      TError,
      { data: CreateCarAttributeCommand },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createCarAttribute>>,
  TError,
  { data: CreateCarAttributeCommand },
  TContext
> => {
  const mutationOptions = getCreateCarAttributeMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const updateCarAttribute = (
  id: number,
  updateCarAttributeCommand: UpdateCarAttributeCommand,
  options?: SecondParameter<typeof api>,
) => {
  return api<void>(
    {
      url: `/api/Admin/V1/CarAttributes/${id}`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: updateCarAttributeCommand,
    },
    options,
  );
};

export const getUpdateCarAttributeMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateCarAttribute>>,
    TError,
    { id: number; data: UpdateCarAttributeCommand },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateCarAttribute>>,
  TError,
  { id: number; data: UpdateCarAttributeCommand },
  TContext
> => {
  const mutationKey = ["updateCarAttribute"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateCarAttribute>>,
    { id: number; data: UpdateCarAttributeCommand }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateCarAttribute(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateCarAttributeMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateCarAttribute>>
>;
export type UpdateCarAttributeMutationBody = UpdateCarAttributeCommand;
export type UpdateCarAttributeMutationError = ErrorType<void>;

export const useUpdateCarAttribute = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateCarAttribute>>,
      TError,
      { id: number; data: UpdateCarAttributeCommand },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateCarAttribute>>,
  TError,
  { id: number; data: UpdateCarAttributeCommand },
  TContext
> => {
  const mutationOptions = getUpdateCarAttributeMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const deleteCarAttribute = (
  id: number,
  options?: SecondParameter<typeof api>,
) => {
  return api<void>(
    { url: `/api/Admin/V1/CarAttributes/${id}`, method: "DELETE" },
    options,
  );
};

export const getDeleteCarAttributeMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteCarAttribute>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteCarAttribute>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["deleteCarAttribute"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteCarAttribute>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return deleteCarAttribute(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteCarAttributeMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteCarAttribute>>
>;

export type DeleteCarAttributeMutationError = ErrorType<void>;

export const useDeleteCarAttribute = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteCarAttribute>>,
      TError,
      { id: number },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteCarAttribute>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getDeleteCarAttributeMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
