/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CarOptionDto,
  CreateCarOptionCommand,
  GetCarOptions2Params,
  GetCarOptionsParams,
  UpdateCarOptionCommand,
} from "../../models";

import { api } from "../../orval-custom-instance";
import type { ErrorType } from "../../orval-custom-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Retrieves a hierarchical list of car options available for filtering and browsing car listings.
Options are organized in a tree structure with parent-child relationships.
            
**Option Types:**
- String (0): Text values like brand names, models
- Number (1): Numeric values like year, mileage
- Boolean (2): True/False values
- Color (3): Color values with potential hex codes
- List (4): Predefined list of options
            
**Usage Examples:**
- GET /api/V1/CarOptions (returns all root options with their children)
- GET /api/V1/CarOptions?parentId=1 (returns specific option and its children)
            
**Common Use Cases:**
- Building filter dropdowns for car search
- Displaying available car features and specifications
- Creating faceted search interfaces
 * @summary Get car options hierarchy for public browsing
 */
export const getCarOptions = (
  params?: GetCarOptionsParams,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<CarOptionDto[]>(
    { url: `/api/V1/CarOptions`, method: "GET", params, signal },
    options,
  );
};

export const getGetCarOptionsQueryKey = (params?: GetCarOptionsParams) => {
  return [`/api/V1/CarOptions`, ...(params ? [params] : [])] as const;
};

export const getGetCarOptionsQueryOptions = <
  TData = Awaited<ReturnType<typeof getCarOptions>>,
  TError = ErrorType<unknown>,
>(
  params?: GetCarOptionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCarOptions>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCarOptionsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCarOptions>>> = ({
    signal,
  }) => getCarOptions(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCarOptions>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCarOptionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCarOptions>>
>;
export type GetCarOptionsQueryError = ErrorType<unknown>;

export function useGetCarOptions<
  TData = Awaited<ReturnType<typeof getCarOptions>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetCarOptionsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCarOptions>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCarOptions>>,
          TError,
          Awaited<ReturnType<typeof getCarOptions>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCarOptions<
  TData = Awaited<ReturnType<typeof getCarOptions>>,
  TError = ErrorType<unknown>,
>(
  params?: GetCarOptionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCarOptions>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCarOptions>>,
          TError,
          Awaited<ReturnType<typeof getCarOptions>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCarOptions<
  TData = Awaited<ReturnType<typeof getCarOptions>>,
  TError = ErrorType<unknown>,
>(
  params?: GetCarOptionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCarOptions>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get car options hierarchy for public browsing
 */

export function useGetCarOptions<
  TData = Awaited<ReturnType<typeof getCarOptions>>,
  TError = ErrorType<unknown>,
>(
  params?: GetCarOptionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCarOptions>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetCarOptionsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getCarOptions2 = (
  params?: GetCarOptions2Params,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<CarOptionDto[]>(
    { url: `/api/Admin/V1/CarOptions`, method: "GET", params, signal },
    options,
  );
};

export const getGetCarOptions2QueryKey = (params?: GetCarOptions2Params) => {
  return [`/api/Admin/V1/CarOptions`, ...(params ? [params] : [])] as const;
};

export const getGetCarOptions2QueryOptions = <
  TData = Awaited<ReturnType<typeof getCarOptions2>>,
  TError = ErrorType<unknown>,
>(
  params?: GetCarOptions2Params,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCarOptions2>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCarOptions2QueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCarOptions2>>> = ({
    signal,
  }) => getCarOptions2(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCarOptions2>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCarOptions2QueryResult = NonNullable<
  Awaited<ReturnType<typeof getCarOptions2>>
>;
export type GetCarOptions2QueryError = ErrorType<unknown>;

export function useGetCarOptions2<
  TData = Awaited<ReturnType<typeof getCarOptions2>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetCarOptions2Params,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCarOptions2>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCarOptions2>>,
          TError,
          Awaited<ReturnType<typeof getCarOptions2>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCarOptions2<
  TData = Awaited<ReturnType<typeof getCarOptions2>>,
  TError = ErrorType<unknown>,
>(
  params?: GetCarOptions2Params,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCarOptions2>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCarOptions2>>,
          TError,
          Awaited<ReturnType<typeof getCarOptions2>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCarOptions2<
  TData = Awaited<ReturnType<typeof getCarOptions2>>,
  TError = ErrorType<unknown>,
>(
  params?: GetCarOptions2Params,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCarOptions2>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetCarOptions2<
  TData = Awaited<ReturnType<typeof getCarOptions2>>,
  TError = ErrorType<unknown>,
>(
  params?: GetCarOptions2Params,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCarOptions2>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetCarOptions2QueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const createCarOption = (
  createCarOptionCommand: CreateCarOptionCommand,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<number>(
    {
      url: `/api/Admin/V1/CarOptions`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createCarOptionCommand,
      signal,
    },
    options,
  );
};

export const getCreateCarOptionMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createCarOption>>,
    TError,
    { data: CreateCarOptionCommand },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createCarOption>>,
  TError,
  { data: CreateCarOptionCommand },
  TContext
> => {
  const mutationKey = ["createCarOption"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createCarOption>>,
    { data: CreateCarOptionCommand }
  > = (props) => {
    const { data } = props ?? {};

    return createCarOption(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateCarOptionMutationResult = NonNullable<
  Awaited<ReturnType<typeof createCarOption>>
>;
export type CreateCarOptionMutationBody = CreateCarOptionCommand;
export type CreateCarOptionMutationError = ErrorType<unknown>;

export const useCreateCarOption = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createCarOption>>,
      TError,
      { data: CreateCarOptionCommand },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createCarOption>>,
  TError,
  { data: CreateCarOptionCommand },
  TContext
> => {
  const mutationOptions = getCreateCarOptionMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const updateCarOption = (
  id: number,
  updateCarOptionCommand: UpdateCarOptionCommand,
  options?: SecondParameter<typeof api>,
) => {
  return api<void>(
    {
      url: `/api/Admin/V1/CarOptions/${id}`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: updateCarOptionCommand,
    },
    options,
  );
};

export const getUpdateCarOptionMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateCarOption>>,
    TError,
    { id: number; data: UpdateCarOptionCommand },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateCarOption>>,
  TError,
  { id: number; data: UpdateCarOptionCommand },
  TContext
> => {
  const mutationKey = ["updateCarOption"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateCarOption>>,
    { id: number; data: UpdateCarOptionCommand }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateCarOption(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateCarOptionMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateCarOption>>
>;
export type UpdateCarOptionMutationBody = UpdateCarOptionCommand;
export type UpdateCarOptionMutationError = ErrorType<void>;

export const useUpdateCarOption = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateCarOption>>,
      TError,
      { id: number; data: UpdateCarOptionCommand },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateCarOption>>,
  TError,
  { id: number; data: UpdateCarOptionCommand },
  TContext
> => {
  const mutationOptions = getUpdateCarOptionMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const deleteCarOption = (
  id: number,
  options?: SecondParameter<typeof api>,
) => {
  return api<void>(
    { url: `/api/Admin/V1/CarOptions/${id}`, method: "DELETE" },
    options,
  );
};

export const getDeleteCarOptionMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteCarOption>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteCarOption>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["deleteCarOption"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteCarOption>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return deleteCarOption(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteCarOptionMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteCarOption>>
>;

export type DeleteCarOptionMutationError = ErrorType<void>;

export const useDeleteCarOption = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteCarOption>>,
      TError,
      { id: number },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteCarOption>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getDeleteCarOptionMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
