/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CreateStaticContentCommand,
  GetStaticContentsParams,
  PaginatedListOfStaticContentDto,
  StaticContentDto,
  UpdateStaticContentCommand,
} from "../../models";

import { api } from "../../orval-custom-instance";
import type { ErrorType } from "../../orval-custom-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Get static content by slug for public display
 */
export const getStaticContentBySlug = (
  slug: string,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<StaticContentDto>(
    { url: `/api/V1/StaticContents/${slug}`, method: "GET", signal },
    options,
  );
};

export const getGetStaticContentBySlugQueryKey = (slug?: string) => {
  return [`/api/V1/StaticContents/${slug}`] as const;
};

export const getGetStaticContentBySlugQueryOptions = <
  TData = Awaited<ReturnType<typeof getStaticContentBySlug>>,
  TError = ErrorType<void>,
>(
  slug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getStaticContentBySlug>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetStaticContentBySlugQueryKey(slug);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getStaticContentBySlug>>
  > = ({ signal }) => getStaticContentBySlug(slug, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!slug,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getStaticContentBySlug>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetStaticContentBySlugQueryResult = NonNullable<
  Awaited<ReturnType<typeof getStaticContentBySlug>>
>;
export type GetStaticContentBySlugQueryError = ErrorType<void>;

export function useGetStaticContentBySlug<
  TData = Awaited<ReturnType<typeof getStaticContentBySlug>>,
  TError = ErrorType<void>,
>(
  slug: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getStaticContentBySlug>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStaticContentBySlug>>,
          TError,
          Awaited<ReturnType<typeof getStaticContentBySlug>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetStaticContentBySlug<
  TData = Awaited<ReturnType<typeof getStaticContentBySlug>>,
  TError = ErrorType<void>,
>(
  slug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getStaticContentBySlug>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStaticContentBySlug>>,
          TError,
          Awaited<ReturnType<typeof getStaticContentBySlug>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetStaticContentBySlug<
  TData = Awaited<ReturnType<typeof getStaticContentBySlug>>,
  TError = ErrorType<void>,
>(
  slug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getStaticContentBySlug>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get static content by slug for public display
 */

export function useGetStaticContentBySlug<
  TData = Awaited<ReturnType<typeof getStaticContentBySlug>>,
  TError = ErrorType<void>,
>(
  slug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getStaticContentBySlug>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetStaticContentBySlugQueryOptions(slug, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get static contents with optional filtering
 */
export const getStaticContents = (
  params?: GetStaticContentsParams,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<PaginatedListOfStaticContentDto>(
    { url: `/api/Admin/V1/StaticContents`, method: "GET", params, signal },
    options,
  );
};

export const getGetStaticContentsQueryKey = (
  params?: GetStaticContentsParams,
) => {
  return [`/api/Admin/V1/StaticContents`, ...(params ? [params] : [])] as const;
};

export const getGetStaticContentsQueryOptions = <
  TData = Awaited<ReturnType<typeof getStaticContents>>,
  TError = ErrorType<unknown>,
>(
  params?: GetStaticContentsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getStaticContents>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetStaticContentsQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getStaticContents>>
  > = ({ signal }) => getStaticContents(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getStaticContents>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetStaticContentsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getStaticContents>>
>;
export type GetStaticContentsQueryError = ErrorType<unknown>;

export function useGetStaticContents<
  TData = Awaited<ReturnType<typeof getStaticContents>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetStaticContentsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getStaticContents>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStaticContents>>,
          TError,
          Awaited<ReturnType<typeof getStaticContents>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetStaticContents<
  TData = Awaited<ReturnType<typeof getStaticContents>>,
  TError = ErrorType<unknown>,
>(
  params?: GetStaticContentsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getStaticContents>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStaticContents>>,
          TError,
          Awaited<ReturnType<typeof getStaticContents>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetStaticContents<
  TData = Awaited<ReturnType<typeof getStaticContents>>,
  TError = ErrorType<unknown>,
>(
  params?: GetStaticContentsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getStaticContents>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get static contents with optional filtering
 */

export function useGetStaticContents<
  TData = Awaited<ReturnType<typeof getStaticContents>>,
  TError = ErrorType<unknown>,
>(
  params?: GetStaticContentsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getStaticContents>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetStaticContentsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Create a new static content
 */
export const createStaticContent = (
  createStaticContentCommand: CreateStaticContentCommand,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<number>(
    {
      url: `/api/Admin/V1/StaticContents`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createStaticContentCommand,
      signal,
    },
    options,
  );
};

export const getCreateStaticContentMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createStaticContent>>,
    TError,
    { data: CreateStaticContentCommand },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createStaticContent>>,
  TError,
  { data: CreateStaticContentCommand },
  TContext
> => {
  const mutationKey = ["createStaticContent"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createStaticContent>>,
    { data: CreateStaticContentCommand }
  > = (props) => {
    const { data } = props ?? {};

    return createStaticContent(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateStaticContentMutationResult = NonNullable<
  Awaited<ReturnType<typeof createStaticContent>>
>;
export type CreateStaticContentMutationBody = CreateStaticContentCommand;
export type CreateStaticContentMutationError = ErrorType<unknown>;

/**
 * @summary Create a new static content
 */
export const useCreateStaticContent = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createStaticContent>>,
      TError,
      { data: CreateStaticContentCommand },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createStaticContent>>,
  TError,
  { data: CreateStaticContentCommand },
  TContext
> => {
  const mutationOptions = getCreateStaticContentMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Get a static content by ID
 */
export const getStaticContentById = (
  id: number,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<StaticContentDto>(
    { url: `/api/Admin/V1/StaticContents/${id}`, method: "GET", signal },
    options,
  );
};

export const getGetStaticContentByIdQueryKey = (id?: number) => {
  return [`/api/Admin/V1/StaticContents/${id}`] as const;
};

export const getGetStaticContentByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getStaticContentById>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getStaticContentById>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetStaticContentByIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getStaticContentById>>
  > = ({ signal }) => getStaticContentById(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getStaticContentById>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetStaticContentByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getStaticContentById>>
>;
export type GetStaticContentByIdQueryError = ErrorType<void>;

export function useGetStaticContentById<
  TData = Awaited<ReturnType<typeof getStaticContentById>>,
  TError = ErrorType<void>,
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getStaticContentById>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStaticContentById>>,
          TError,
          Awaited<ReturnType<typeof getStaticContentById>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetStaticContentById<
  TData = Awaited<ReturnType<typeof getStaticContentById>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getStaticContentById>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStaticContentById>>,
          TError,
          Awaited<ReturnType<typeof getStaticContentById>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetStaticContentById<
  TData = Awaited<ReturnType<typeof getStaticContentById>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getStaticContentById>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get a static content by ID
 */

export function useGetStaticContentById<
  TData = Awaited<ReturnType<typeof getStaticContentById>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getStaticContentById>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetStaticContentByIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Update an existing static content
 */
export const updateStaticContent = (
  id: number,
  updateStaticContentCommand: UpdateStaticContentCommand,
  options?: SecondParameter<typeof api>,
) => {
  return api<void>(
    {
      url: `/api/Admin/V1/StaticContents/${id}`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: updateStaticContentCommand,
    },
    options,
  );
};

export const getUpdateStaticContentMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateStaticContent>>,
    TError,
    { id: number; data: UpdateStaticContentCommand },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateStaticContent>>,
  TError,
  { id: number; data: UpdateStaticContentCommand },
  TContext
> => {
  const mutationKey = ["updateStaticContent"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateStaticContent>>,
    { id: number; data: UpdateStaticContentCommand }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateStaticContent(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateStaticContentMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateStaticContent>>
>;
export type UpdateStaticContentMutationBody = UpdateStaticContentCommand;
export type UpdateStaticContentMutationError = ErrorType<void>;

/**
 * @summary Update an existing static content
 */
export const useUpdateStaticContent = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateStaticContent>>,
      TError,
      { id: number; data: UpdateStaticContentCommand },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateStaticContent>>,
  TError,
  { id: number; data: UpdateStaticContentCommand },
  TContext
> => {
  const mutationOptions = getUpdateStaticContentMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Delete a static content
 */
export const deleteStaticContent = (
  id: number,
  options?: SecondParameter<typeof api>,
) => {
  return api<void>(
    { url: `/api/Admin/V1/StaticContents/${id}`, method: "DELETE" },
    options,
  );
};

export const getDeleteStaticContentMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteStaticContent>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteStaticContent>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["deleteStaticContent"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteStaticContent>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return deleteStaticContent(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteStaticContentMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteStaticContent>>
>;

export type DeleteStaticContentMutationError = ErrorType<void>;

/**
 * @summary Delete a static content
 */
export const useDeleteStaticContent = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteStaticContent>>,
      TError,
      { id: number },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteStaticContent>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getDeleteStaticContentMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
