/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CarListingDto,
  CreateCarListingCommand,
  GetCarListings2Params,
  GetCarListingsParams,
  PaginatedListOfCarListingDto,
  PaginatedListOfPublicCarListingDto,
  PublicCarListingDto,
  UpdateCarListingCommand,
} from "../../models";

import { api } from "../../orval-custom-instance";
import type { ErrorType } from "../../orval-custom-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Retrieves a paginated list of car listings for public viewing. Supports filtering by various criteria including dynamic attribute filters, sorting, and pagination.
            
**Attribute Filters:**
Use format: ?attribute[attributeId]=value
Examples:
- ?attribute[1]=red (filters where attribute with ID 1 contains 'red')
- ?attribute[2]=automatic (filters where attribute with ID 2 contains 'automatic')
- ?attribute[1]=red&attribute[2]=automatic (combines multiple filters)
            
Where attributeId is the CarAttributeId and value is what to filter by (contains match).
            
**Sorting:**
Use ?sortBy=field&sortDirection=asc|desc
Supported fields: stockNumber, price, salePrice, registrationDate, manufacturerName, carModelName
Default sort: stockNumber (ascending)
            
**Examples:**
- GET /api/V1/CarListings?pageNumber=1&pageSize=20
- GET /api/V1/CarListings?isSold=false&sortBy=price&sortDirection=asc
- GET /api/V1/CarListings?isSpecialOffer=true&pageSize=5
- GET /api/V1/CarListings?attribute[1]=sedan&attribute[2]=automatic
 * @summary Get car listings with optional filtering, sorting, and pagination
 */
export const getCarListings = (
  params?: GetCarListingsParams,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<PaginatedListOfPublicCarListingDto>(
    { url: `/api/V1/CarListings`, method: "GET", params, signal },
    options,
  );
};

export const getGetCarListingsQueryKey = (params?: GetCarListingsParams) => {
  return [`/api/V1/CarListings`, ...(params ? [params] : [])] as const;
};

export const getGetCarListingsQueryOptions = <
  TData = Awaited<ReturnType<typeof getCarListings>>,
  TError = ErrorType<unknown>,
>(
  params?: GetCarListingsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCarListings>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCarListingsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCarListings>>> = ({
    signal,
  }) => getCarListings(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCarListings>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCarListingsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCarListings>>
>;
export type GetCarListingsQueryError = ErrorType<unknown>;

export function useGetCarListings<
  TData = Awaited<ReturnType<typeof getCarListings>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetCarListingsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCarListings>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCarListings>>,
          TError,
          Awaited<ReturnType<typeof getCarListings>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCarListings<
  TData = Awaited<ReturnType<typeof getCarListings>>,
  TError = ErrorType<unknown>,
>(
  params?: GetCarListingsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCarListings>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCarListings>>,
          TError,
          Awaited<ReturnType<typeof getCarListings>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCarListings<
  TData = Awaited<ReturnType<typeof getCarListings>>,
  TError = ErrorType<unknown>,
>(
  params?: GetCarListingsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCarListings>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get car listings with optional filtering, sorting, and pagination
 */

export function useGetCarListings<
  TData = Awaited<ReturnType<typeof getCarListings>>,
  TError = ErrorType<unknown>,
>(
  params?: GetCarListingsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCarListings>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetCarListingsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get a car listing by slug
 */
export const getCarListingBySlug = (
  slug: string,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<PublicCarListingDto>(
    { url: `/api/V1/CarListings/${slug}`, method: "GET", signal },
    options,
  );
};

export const getGetCarListingBySlugQueryKey = (slug?: string) => {
  return [`/api/V1/CarListings/${slug}`] as const;
};

export const getGetCarListingBySlugQueryOptions = <
  TData = Awaited<ReturnType<typeof getCarListingBySlug>>,
  TError = ErrorType<void>,
>(
  slug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCarListingBySlug>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetCarListingBySlugQueryKey(slug);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getCarListingBySlug>>
  > = ({ signal }) => getCarListingBySlug(slug, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!slug,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getCarListingBySlug>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCarListingBySlugQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCarListingBySlug>>
>;
export type GetCarListingBySlugQueryError = ErrorType<void>;

export function useGetCarListingBySlug<
  TData = Awaited<ReturnType<typeof getCarListingBySlug>>,
  TError = ErrorType<void>,
>(
  slug: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCarListingBySlug>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCarListingBySlug>>,
          TError,
          Awaited<ReturnType<typeof getCarListingBySlug>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCarListingBySlug<
  TData = Awaited<ReturnType<typeof getCarListingBySlug>>,
  TError = ErrorType<void>,
>(
  slug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCarListingBySlug>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCarListingBySlug>>,
          TError,
          Awaited<ReturnType<typeof getCarListingBySlug>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCarListingBySlug<
  TData = Awaited<ReturnType<typeof getCarListingBySlug>>,
  TError = ErrorType<void>,
>(
  slug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCarListingBySlug>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get a car listing by slug
 */

export function useGetCarListingBySlug<
  TData = Awaited<ReturnType<typeof getCarListingBySlug>>,
  TError = ErrorType<void>,
>(
  slug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCarListingBySlug>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetCarListingBySlugQueryOptions(slug, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Retrieves a paginated list of car listings. Supports filtering by various criteria including dynamic attribute filters.
            
**Attribute Filters:**
Use format: ?attribute[attributeId]=value
Examples:
- ?attribute[1]=red (filters where attribute with ID 1 contains 'red')
- ?attribute[2]=automatic (filters where attribute with ID 2 contains 'automatic')
- ?attribute[1]=red&attribute[2]=automatic (combines multiple filters)
            
Where attributeId is the CarAttributeId and value is what to filter by (contains match).
 * @summary Get car listings with optional filtering
 */
export const getCarListings2 = (
  params?: GetCarListings2Params,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<PaginatedListOfCarListingDto>(
    { url: `/api/Admin/V1/CarListings`, method: "GET", params, signal },
    options,
  );
};

export const getGetCarListings2QueryKey = (params?: GetCarListings2Params) => {
  return [`/api/Admin/V1/CarListings`, ...(params ? [params] : [])] as const;
};

export const getGetCarListings2QueryOptions = <
  TData = Awaited<ReturnType<typeof getCarListings2>>,
  TError = ErrorType<unknown>,
>(
  params?: GetCarListings2Params,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCarListings2>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCarListings2QueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCarListings2>>> = ({
    signal,
  }) => getCarListings2(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCarListings2>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCarListings2QueryResult = NonNullable<
  Awaited<ReturnType<typeof getCarListings2>>
>;
export type GetCarListings2QueryError = ErrorType<unknown>;

export function useGetCarListings2<
  TData = Awaited<ReturnType<typeof getCarListings2>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetCarListings2Params,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCarListings2>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCarListings2>>,
          TError,
          Awaited<ReturnType<typeof getCarListings2>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCarListings2<
  TData = Awaited<ReturnType<typeof getCarListings2>>,
  TError = ErrorType<unknown>,
>(
  params?: GetCarListings2Params,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCarListings2>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCarListings2>>,
          TError,
          Awaited<ReturnType<typeof getCarListings2>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCarListings2<
  TData = Awaited<ReturnType<typeof getCarListings2>>,
  TError = ErrorType<unknown>,
>(
  params?: GetCarListings2Params,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCarListings2>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get car listings with optional filtering
 */

export function useGetCarListings2<
  TData = Awaited<ReturnType<typeof getCarListings2>>,
  TError = ErrorType<unknown>,
>(
  params?: GetCarListings2Params,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCarListings2>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetCarListings2QueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const createCarListing = (
  createCarListingCommand: CreateCarListingCommand,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<number>(
    {
      url: `/api/Admin/V1/CarListings`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createCarListingCommand,
      signal,
    },
    options,
  );
};

export const getCreateCarListingMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createCarListing>>,
    TError,
    { data: CreateCarListingCommand },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createCarListing>>,
  TError,
  { data: CreateCarListingCommand },
  TContext
> => {
  const mutationKey = ["createCarListing"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createCarListing>>,
    { data: CreateCarListingCommand }
  > = (props) => {
    const { data } = props ?? {};

    return createCarListing(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateCarListingMutationResult = NonNullable<
  Awaited<ReturnType<typeof createCarListing>>
>;
export type CreateCarListingMutationBody = CreateCarListingCommand;
export type CreateCarListingMutationError = ErrorType<unknown>;

export const useCreateCarListing = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createCarListing>>,
      TError,
      { data: CreateCarListingCommand },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createCarListing>>,
  TError,
  { data: CreateCarListingCommand },
  TContext
> => {
  const mutationOptions = getCreateCarListingMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Get a car listing by ID
 */
export const getCarListingById = (
  id: number,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<CarListingDto>(
    { url: `/api/Admin/V1/CarListings/${id}`, method: "GET", signal },
    options,
  );
};

export const getGetCarListingByIdQueryKey = (id?: number) => {
  return [`/api/Admin/V1/CarListings/${id}`] as const;
};

export const getGetCarListingByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getCarListingById>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCarListingById>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCarListingByIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getCarListingById>>
  > = ({ signal }) => getCarListingById(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getCarListingById>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCarListingByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCarListingById>>
>;
export type GetCarListingByIdQueryError = ErrorType<void>;

export function useGetCarListingById<
  TData = Awaited<ReturnType<typeof getCarListingById>>,
  TError = ErrorType<void>,
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCarListingById>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCarListingById>>,
          TError,
          Awaited<ReturnType<typeof getCarListingById>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCarListingById<
  TData = Awaited<ReturnType<typeof getCarListingById>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCarListingById>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCarListingById>>,
          TError,
          Awaited<ReturnType<typeof getCarListingById>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCarListingById<
  TData = Awaited<ReturnType<typeof getCarListingById>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCarListingById>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get a car listing by ID
 */

export function useGetCarListingById<
  TData = Awaited<ReturnType<typeof getCarListingById>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCarListingById>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetCarListingByIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const updateCarListing = (
  id: number,
  updateCarListingCommand: UpdateCarListingCommand,
  options?: SecondParameter<typeof api>,
) => {
  return api<void>(
    {
      url: `/api/Admin/V1/CarListings/${id}`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: updateCarListingCommand,
    },
    options,
  );
};

export const getUpdateCarListingMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateCarListing>>,
    TError,
    { id: number; data: UpdateCarListingCommand },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateCarListing>>,
  TError,
  { id: number; data: UpdateCarListingCommand },
  TContext
> => {
  const mutationKey = ["updateCarListing"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateCarListing>>,
    { id: number; data: UpdateCarListingCommand }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateCarListing(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateCarListingMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateCarListing>>
>;
export type UpdateCarListingMutationBody = UpdateCarListingCommand;
export type UpdateCarListingMutationError = ErrorType<void>;

export const useUpdateCarListing = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateCarListing>>,
      TError,
      { id: number; data: UpdateCarListingCommand },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateCarListing>>,
  TError,
  { id: number; data: UpdateCarListingCommand },
  TContext
> => {
  const mutationOptions = getUpdateCarListingMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const deleteCarListing = (
  id: number,
  options?: SecondParameter<typeof api>,
) => {
  return api<void>(
    { url: `/api/Admin/V1/CarListings/${id}`, method: "DELETE" },
    options,
  );
};

export const getDeleteCarListingMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteCarListing>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteCarListing>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["deleteCarListing"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteCarListing>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return deleteCarListing(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteCarListingMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteCarListing>>
>;

export type DeleteCarListingMutationError = ErrorType<void>;

export const useDeleteCarListing = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteCarListing>>,
      TError,
      { id: number },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteCarListing>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getDeleteCarListingMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const duplicateCarListing = (
  id: number,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<number>(
    {
      url: `/api/Admin/V1/CarListings/${id}/duplicate`,
      method: "POST",
      signal,
    },
    options,
  );
};

export const getDuplicateCarListingMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof duplicateCarListing>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof duplicateCarListing>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["duplicateCarListing"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof duplicateCarListing>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return duplicateCarListing(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DuplicateCarListingMutationResult = NonNullable<
  Awaited<ReturnType<typeof duplicateCarListing>>
>;

export type DuplicateCarListingMutationError = ErrorType<void>;

export const useDuplicateCarListing = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof duplicateCarListing>>,
      TError,
      { id: number },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof duplicateCarListing>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getDuplicateCarListingMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
