/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CreateSliderCommand,
  GetSlidersAllParams,
  GetSlidersParams,
  PaginatedListOfSliderDto,
  PublicSliderDto,
  SliderDto,
  UpdateSliderCommand,
} from "../../models";

import { api } from "../../orval-custom-instance";
import type { ErrorType } from "../../orval-custom-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Get all enabled sliders for public display
 */
export const getSlidersAll = (
  params?: GetSlidersAllParams,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<PublicSliderDto[]>(
    { url: `/api/V1/Sliders`, method: "GET", params, signal },
    options,
  );
};

export const getGetSlidersAllQueryKey = (params?: GetSlidersAllParams) => {
  return [`/api/V1/Sliders`, ...(params ? [params] : [])] as const;
};

export const getGetSlidersAllQueryOptions = <
  TData = Awaited<ReturnType<typeof getSlidersAll>>,
  TError = ErrorType<unknown>,
>(
  params?: GetSlidersAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSlidersAll>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetSlidersAllQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSlidersAll>>> = ({
    signal,
  }) => getSlidersAll(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getSlidersAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetSlidersAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSlidersAll>>
>;
export type GetSlidersAllQueryError = ErrorType<unknown>;

export function useGetSlidersAll<
  TData = Awaited<ReturnType<typeof getSlidersAll>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetSlidersAllParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSlidersAll>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSlidersAll>>,
          TError,
          Awaited<ReturnType<typeof getSlidersAll>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetSlidersAll<
  TData = Awaited<ReturnType<typeof getSlidersAll>>,
  TError = ErrorType<unknown>,
>(
  params?: GetSlidersAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSlidersAll>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSlidersAll>>,
          TError,
          Awaited<ReturnType<typeof getSlidersAll>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetSlidersAll<
  TData = Awaited<ReturnType<typeof getSlidersAll>>,
  TError = ErrorType<unknown>,
>(
  params?: GetSlidersAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSlidersAll>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get all enabled sliders for public display
 */

export function useGetSlidersAll<
  TData = Awaited<ReturnType<typeof getSlidersAll>>,
  TError = ErrorType<unknown>,
>(
  params?: GetSlidersAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSlidersAll>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetSlidersAllQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get sliders with optional filtering
 */
export const getSliders = (
  params?: GetSlidersParams,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<PaginatedListOfSliderDto>(
    { url: `/api/Admin/V1/Sliders`, method: "GET", params, signal },
    options,
  );
};

export const getGetSlidersQueryKey = (params?: GetSlidersParams) => {
  return [`/api/Admin/V1/Sliders`, ...(params ? [params] : [])] as const;
};

export const getGetSlidersQueryOptions = <
  TData = Awaited<ReturnType<typeof getSliders>>,
  TError = ErrorType<unknown>,
>(
  params?: GetSlidersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSliders>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetSlidersQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSliders>>> = ({
    signal,
  }) => getSliders(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getSliders>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetSlidersQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSliders>>
>;
export type GetSlidersQueryError = ErrorType<unknown>;

export function useGetSliders<
  TData = Awaited<ReturnType<typeof getSliders>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetSlidersParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSliders>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSliders>>,
          TError,
          Awaited<ReturnType<typeof getSliders>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetSliders<
  TData = Awaited<ReturnType<typeof getSliders>>,
  TError = ErrorType<unknown>,
>(
  params?: GetSlidersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSliders>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSliders>>,
          TError,
          Awaited<ReturnType<typeof getSliders>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetSliders<
  TData = Awaited<ReturnType<typeof getSliders>>,
  TError = ErrorType<unknown>,
>(
  params?: GetSlidersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSliders>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get sliders with optional filtering
 */

export function useGetSliders<
  TData = Awaited<ReturnType<typeof getSliders>>,
  TError = ErrorType<unknown>,
>(
  params?: GetSlidersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSliders>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetSlidersQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Create a new slider
 */
export const createSlider = (
  createSliderCommand: CreateSliderCommand,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<number>(
    {
      url: `/api/Admin/V1/Sliders`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createSliderCommand,
      signal,
    },
    options,
  );
};

export const getCreateSliderMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createSlider>>,
    TError,
    { data: CreateSliderCommand },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createSlider>>,
  TError,
  { data: CreateSliderCommand },
  TContext
> => {
  const mutationKey = ["createSlider"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createSlider>>,
    { data: CreateSliderCommand }
  > = (props) => {
    const { data } = props ?? {};

    return createSlider(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateSliderMutationResult = NonNullable<
  Awaited<ReturnType<typeof createSlider>>
>;
export type CreateSliderMutationBody = CreateSliderCommand;
export type CreateSliderMutationError = ErrorType<unknown>;

/**
 * @summary Create a new slider
 */
export const useCreateSlider = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createSlider>>,
      TError,
      { data: CreateSliderCommand },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createSlider>>,
  TError,
  { data: CreateSliderCommand },
  TContext
> => {
  const mutationOptions = getCreateSliderMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Get a slider by ID
 */
export const getSliderById = (
  id: number,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<SliderDto>(
    { url: `/api/Admin/V1/Sliders/${id}`, method: "GET", signal },
    options,
  );
};

export const getGetSliderByIdQueryKey = (id?: number) => {
  return [`/api/Admin/V1/Sliders/${id}`] as const;
};

export const getGetSliderByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getSliderById>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSliderById>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetSliderByIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSliderById>>> = ({
    signal,
  }) => getSliderById(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getSliderById>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetSliderByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSliderById>>
>;
export type GetSliderByIdQueryError = ErrorType<void>;

export function useGetSliderById<
  TData = Awaited<ReturnType<typeof getSliderById>>,
  TError = ErrorType<void>,
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSliderById>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSliderById>>,
          TError,
          Awaited<ReturnType<typeof getSliderById>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetSliderById<
  TData = Awaited<ReturnType<typeof getSliderById>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSliderById>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSliderById>>,
          TError,
          Awaited<ReturnType<typeof getSliderById>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetSliderById<
  TData = Awaited<ReturnType<typeof getSliderById>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSliderById>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get a slider by ID
 */

export function useGetSliderById<
  TData = Awaited<ReturnType<typeof getSliderById>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSliderById>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetSliderByIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Update an existing slider
 */
export const updateSlider = (
  id: number,
  updateSliderCommand: UpdateSliderCommand,
  options?: SecondParameter<typeof api>,
) => {
  return api<void>(
    {
      url: `/api/Admin/V1/Sliders/${id}`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: updateSliderCommand,
    },
    options,
  );
};

export const getUpdateSliderMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateSlider>>,
    TError,
    { id: number; data: UpdateSliderCommand },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateSlider>>,
  TError,
  { id: number; data: UpdateSliderCommand },
  TContext
> => {
  const mutationKey = ["updateSlider"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateSlider>>,
    { id: number; data: UpdateSliderCommand }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateSlider(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateSliderMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateSlider>>
>;
export type UpdateSliderMutationBody = UpdateSliderCommand;
export type UpdateSliderMutationError = ErrorType<void>;

/**
 * @summary Update an existing slider
 */
export const useUpdateSlider = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateSlider>>,
      TError,
      { id: number; data: UpdateSliderCommand },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateSlider>>,
  TError,
  { id: number; data: UpdateSliderCommand },
  TContext
> => {
  const mutationOptions = getUpdateSliderMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Delete a slider
 */
export const deleteSlider = (
  id: number,
  options?: SecondParameter<typeof api>,
) => {
  return api<void>(
    { url: `/api/Admin/V1/Sliders/${id}`, method: "DELETE" },
    options,
  );
};

export const getDeleteSliderMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteSlider>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteSlider>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["deleteSlider"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteSlider>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return deleteSlider(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteSliderMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteSlider>>
>;

export type DeleteSliderMutationError = ErrorType<void>;

/**
 * @summary Delete a slider
 */
export const useDeleteSlider = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteSlider>>,
      TError,
      { id: number },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteSlider>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getDeleteSliderMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
