/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  GetApiAdminV1ImagesParams,
  PaginatedListOfImageDto,
  PostApiAdminV1ImagesBody,
  PostApiAdminV1ImagesParams,
} from "../../models";

import { api } from "../../orval-custom-instance";
import type { ErrorType } from "../../orval-custom-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const postApiAdminV1Images = (
  postApiAdminV1ImagesBody: PostApiAdminV1ImagesBody,
  params?: PostApiAdminV1ImagesParams,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  const formData = new FormData();
  if (
    postApiAdminV1ImagesBody.file !== undefined &&
    postApiAdminV1ImagesBody.file !== null
  ) {
    formData.append(`file`, postApiAdminV1ImagesBody.file);
  }

  return api<number>(
    {
      url: `/api/Admin/V1/Images`,
      method: "POST",
      headers: { "Content-Type": "multipart/form-data" },
      data: formData,
      params,
      signal,
    },
    options,
  );
};

export const getPostApiAdminV1ImagesMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiAdminV1Images>>,
    TError,
    { data: PostApiAdminV1ImagesBody; params?: PostApiAdminV1ImagesParams },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiAdminV1Images>>,
  TError,
  { data: PostApiAdminV1ImagesBody; params?: PostApiAdminV1ImagesParams },
  TContext
> => {
  const mutationKey = ["postApiAdminV1Images"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiAdminV1Images>>,
    { data: PostApiAdminV1ImagesBody; params?: PostApiAdminV1ImagesParams }
  > = (props) => {
    const { data, params } = props ?? {};

    return postApiAdminV1Images(data, params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiAdminV1ImagesMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiAdminV1Images>>
>;
export type PostApiAdminV1ImagesMutationBody = PostApiAdminV1ImagesBody;
export type PostApiAdminV1ImagesMutationError = ErrorType<unknown>;

export const usePostApiAdminV1Images = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiAdminV1Images>>,
      TError,
      { data: PostApiAdminV1ImagesBody; params?: PostApiAdminV1ImagesParams },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiAdminV1Images>>,
  TError,
  { data: PostApiAdminV1ImagesBody; params?: PostApiAdminV1ImagesParams },
  TContext
> => {
  const mutationOptions = getPostApiAdminV1ImagesMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const getApiAdminV1Images = (
  params?: GetApiAdminV1ImagesParams,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<PaginatedListOfImageDto>(
    { url: `/api/Admin/V1/Images`, method: "GET", params, signal },
    options,
  );
};

export const getGetApiAdminV1ImagesQueryKey = (
  params?: GetApiAdminV1ImagesParams,
) => {
  return [`/api/Admin/V1/Images`, ...(params ? [params] : [])] as const;
};

export const getGetApiAdminV1ImagesQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiAdminV1Images>>,
  TError = ErrorType<unknown>,
>(
  params?: GetApiAdminV1ImagesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiAdminV1Images>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiAdminV1ImagesQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiAdminV1Images>>
  > = ({ signal }) => getApiAdminV1Images(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiAdminV1Images>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiAdminV1ImagesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiAdminV1Images>>
>;
export type GetApiAdminV1ImagesQueryError = ErrorType<unknown>;

export function useGetApiAdminV1Images<
  TData = Awaited<ReturnType<typeof getApiAdminV1Images>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetApiAdminV1ImagesParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiAdminV1Images>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAdminV1Images>>,
          TError,
          Awaited<ReturnType<typeof getApiAdminV1Images>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiAdminV1Images<
  TData = Awaited<ReturnType<typeof getApiAdminV1Images>>,
  TError = ErrorType<unknown>,
>(
  params?: GetApiAdminV1ImagesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiAdminV1Images>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAdminV1Images>>,
          TError,
          Awaited<ReturnType<typeof getApiAdminV1Images>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiAdminV1Images<
  TData = Awaited<ReturnType<typeof getApiAdminV1Images>>,
  TError = ErrorType<unknown>,
>(
  params?: GetApiAdminV1ImagesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiAdminV1Images>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiAdminV1Images<
  TData = Awaited<ReturnType<typeof getApiAdminV1Images>>,
  TError = ErrorType<unknown>,
>(
  params?: GetApiAdminV1ImagesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiAdminV1Images>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiAdminV1ImagesQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const deleteApiAdminV1Images = (
  id: number,
  options?: SecondParameter<typeof api>,
) => {
  return api<void>(
    { url: `/api/Admin/V1/Images/${id}`, method: "DELETE" },
    options,
  );
};

export const getDeleteApiAdminV1ImagesMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteApiAdminV1Images>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteApiAdminV1Images>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["deleteApiAdminV1Images"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteApiAdminV1Images>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return deleteApiAdminV1Images(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteApiAdminV1ImagesMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteApiAdminV1Images>>
>;

export type DeleteApiAdminV1ImagesMutationError = ErrorType<unknown>;

export const useDeleteApiAdminV1Images = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteApiAdminV1Images>>,
      TError,
      { id: number },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteApiAdminV1Images>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getDeleteApiAdminV1ImagesMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
